// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1a319528ca7ac532fecf9b38dcd4d55501082b39c06dd3af3debbacb03fd2bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
