# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: detection
defmodule E2e.DetectionTest do
  use ExUnit.Case, async: false

  describe "detect_mime_bytes_html" do
    test "detect_mime_bytes_html" do
      content = File.read!("../../test_documents/html/html.html")
      {:ok, result} = Kreuzberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "detect_mime_bytes_pdf" do
    test "detect_mime_bytes_pdf" do
      content = File.read!("../../test_documents/pdf/fake_memo.pdf")
      {:ok, result} = Kreuzberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "detect_mime_bytes_png" do
    test "detect_mime_bytes_png" do
      content = File.read!("../../test_documents/images/test_hello_world.png")
      {:ok, result} = Kreuzberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "get_extensions_unknown_mime" do
    test "get_extensions_unknown_mime" do
      assert {:error, _} = Kreuzberg.get_extensions_for_mime("application/x-totally-unknown")
    end
  end
end
