# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2daa457e3ac8514651b53b5ce691483e4e329f240071b5b17e913c5a3dd9672a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Kreuzberg.embed_texts(["Hello", "World"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
