# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_async_pending
defmodule E2e.EmbedAsyncPendingTest do
  use ExUnit.Case, async: false

  describe "embed_texts_async_empty_input" do
    test "embed_texts_async_empty_input" do
      {:ok, result} = Kreuzberg.embed_texts_async([])
      assert length(result) == 0
    end
  end

  describe "embed_texts_async_happy" do
    test "embed_texts_async_happy" do
      {:ok, result} = Kreuzberg.embed_texts_async(["First", "Second"])
      assert length(result) >= 2
    end
  end

  describe "embed_texts_async_preset_switch" do
    test "embed_texts_async_preset_switch" do
      {:ok, result} = Kreuzberg.embed_texts_async(["Text"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
