# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_async_pending
defmodule E2e.EmbedAsyncPendingTest do
  use ExUnit.Case, async: false

  describe "embed_texts_async_empty_input" do
    test "embed_texts_async_empty_input" do
      {:ok, result} = Kreuzberg.embed_texts_async([], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
      assert length(result) == 0
    end
  end

  describe "embed_texts_async_happy" do
    test "embed_texts_async_happy" do
      {:ok, result} = Kreuzberg.embed_texts_async(["First", "Second"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
      assert length(result) >= 2
    end
  end

  describe "embed_texts_async_preset_switch" do
    test "embed_texts_async_preset_switch" do
      {:ok, result} = Kreuzberg.embed_texts_async(["Text"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
