# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6fe4097c5c9265f7cbc325fb7d88dd75af5911ad50f822cd865e11bb40811599
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Kreuzberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Kreuzberg.list_ocr_backends()
    end
  end
end
