# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
