// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: mime_utilities.</summary>
    public class MimeUtilitiesTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_MimeDetectBytes()
        {
            // Detect MIME type from file bytes
            var result = KreuzbergLib.DetectMimeTypeFromBytes(System.IO.File.ReadAllBytes("pdf/fake_memo.pdf"));
            // skipped: field 'result' not available on result type
        }

        [Fact]
        public void Test_MimeDetectImage()
        {
            // Detect MIME type from PNG image bytes
            var result = KreuzbergLib.DetectMimeTypeFromBytes(System.IO.File.ReadAllBytes("images/test_hello_world.png"));
            // skipped: field 'result' not available on result type
        }

        [Fact]
        public void Test_MimeGetExtensions()
        {
            // Get file extensions for a MIME type
            var result = KreuzbergLib.GetExtensionsForMime("application/pdf");
            // skipped: field 'result' not available on result type
        }


    }
}
