// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78fc3df930d44f0e4df4960789e21ab69a266bc3223aee14c7d0257c78b90d8d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: ocr_backend_management.</summary>
    public class OcrBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_OcrBackendsClear()
        {
            // Clear all OCR backends and verify list is empty
            KreuzbergLib.ClearOcrBackends();
        }

        [Fact]
        public void Test_OcrBackendsList()
        {
            // List all registered OCR backends
            var result = KreuzbergLib.ListOcrBackends();

        }


    }
}
