// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: registry.</summary>
    public class RegistryTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ListDocumentExtractors()
        {
            // List document extractors
            var result = KreuzbergLib.ListDocumentExtractors();

        }

        [Fact]
        public void Test_ListEmbeddingBackends()
        {
            // List embedding backends
            var result = KreuzbergLib.ListEmbeddingBackends();

        }

        [Fact]
        public void Test_ListOcrBackends()
        {
            // List OCR backends
            var result = KreuzbergLib.ListOcrBackends();

        }

        [Fact]
        public void Test_ListPostProcessors()
        {
            // List post-processors
            var result = KreuzbergLib.ListPostProcessors();

        }

        [Fact]
        public void Test_ListRenderers()
        {
            // List renderers
            var result = KreuzbergLib.ListRenderers();

        }

        [Fact]
        public void Test_ListValidators()
        {
            // List validators
            var result = KreuzbergLib.ListValidators();

        }


    }
}
