// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embedding_backend_management

use kreuzberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
