// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embed_extra

use kreuzberg::embed_texts;
use kreuzberg::EmbeddingConfig;

#[test]
fn test_embed_texts_batch() {
    // Batch embed texts
    let texts_json: serde_json::Value = serde_json::from_str(r#"["Hello","World"]"#).unwrap();
    let texts = serde_json::from_value::<Vec<String>>(texts_json).unwrap();
    let config_json: serde_json::Value =
        serde_json::from_str(r#"{"model":{"name":"balanced","type":"preset"}}"#).unwrap();
    let config: EmbeddingConfig = serde_json::from_value(config_json).unwrap();
    let _ = embed_texts(texts, &config).expect("should succeed");
}
