// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: post_processor_management

use kreuzberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let _ = clear_post_processors();
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
