// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: registry_operations

use kreuzberg::get_extensions_for_mime;

#[test]
fn test_extensions_docx() {
    // Get file extensions for DOCX MIME type
    let mime_type = r#"application/vnd.openxmlformats-officedocument.wordprocessingml.document"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_html() {
    // Get file extensions for HTML MIME type
    let mime_type = r#"text/html"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_pdf() {
    // Get file extensions for PDF MIME type
    let mime_type = r#"application/pdf"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}
