// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: renderer_management

use kreuzberg::{clear_renderers, list_renderers};

#[test]
fn test_renderers_clear() {
    // Clear all renderers and verify list is empty
    let _ = clear_renderers();
}

#[test]
fn test_renderers_list() {
    // List all registered renderers
    let _ = list_renderers();
}
