<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: embed_async_pending. */
final class EmbedAsyncPendingTest extends TestCase
{

    /** embed_texts_async: empty text list */
    public function test_embed_texts_async_empty_input(): void
    {
        $result = Kreuzberg::embedTextsAsync([], \Kreuzberg\EmbeddingConfig::from_json('{}'));

        $this->assertCount(0, $result);

    }


    /** embed_texts_async: basic async embedding */
    public function test_embed_texts_async_happy(): void
    {
        $result = Kreuzberg::embedTextsAsync(["First", "Second"], \Kreuzberg\EmbeddingConfig::from_json('{}'));

        $this->assertGreaterThanOrEqual(2, count($result));

    }


    /** embed_texts_async: preset override */
    public function test_embed_texts_async_preset_switch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Text"], $config);


    }

}
