<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\EmbeddingConfig;

/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{

    /** Batch embed texts */
    public function test_embed_texts_batch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Hello", "World"], $config);


    }

}
