<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\EmbeddingConfig;

/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{

    /** Batch embed texts */
    public function test_embed_texts_batch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Hello", "World"], $config);


    }

}
