<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d7dc7690b9785b1948628889b44fe013a83380ab865b26eba38b3fe7902e36a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{

    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearPostProcessors();


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listPostProcessors();


    }

}
