<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{

    /** List document extractors */
    public function test_list_document_extractors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listDocumentExtractors();


    }


    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listEmbeddingBackends();


    }


    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }


    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listPostProcessors();


    }


    /** List renderers */
    public function test_list_renderers(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();


    }


    /** List validators */
    public function test_list_validators(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
