<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{

    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearRenderers();


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();


    }

}
