// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Properties for anchored drawings.
 */
data class AnchorProperties(
    val behindDoc: Boolean,
    val layoutInCell: Boolean,
    val relativeHeight: Long?,
    val positionH: String?,
    val positionV: String?,
    val wrapType: String
)
