// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * How chunk size is measured.
 *
 * Defaults to `Characters` (Unicode character count). When using token-based sizing,
 * chunks are sized by token count according to the specified tokenizer.
 *
 * Token-based sizing uses HuggingFace tokenizers loaded at runtime. Any tokenizer
 * available on HuggingFace Hub can be used, including OpenAI-compatible tokenizers
 * (e.g., `Xenova/gpt-4o`, `Xenova/cl100k_base`).
 */
sealed class ChunkSizing {
    object Characters : ChunkSizing()
    data class Tokenizer(
        val model: String,
        val cacheDir: Path?
    ) : ChunkSizing()
}
