// Generated by alef. Do not edit by hand.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Citation file metadata (RIS, PubMed, EndNote). */
data class CitationMetadata(
    /** Total number of citation records in the file. */
    val citationCount: Long = 0L,
    /** Detected citation file format (e.g. `"ris"`, `"pubmed"`, `"endnote"`). */
    val format: String? = null,
    /** Author names collected across all citation records. */
    val authors: List<String> = emptyList(),
    /** Earliest and latest publication years found in the file. */
    val yearRange: YearRange? = null,
    /** DOI identifiers found in the citation records. */
    val dois: List<String> = emptyList(),
    /** Keywords collected from all citation records. */
    val keywords: List<String> = emptyList(),
)
