// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Request parameters for MIME type detection.
 */
data class DetectMimeTypeParams(
    val path: String,
    val useContent: Boolean
)
