// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * A detected structural boundary in the text.
 */
data class DetectedBoundary(
    val byteOffset: Long,
    val isHeader: Boolean
)
