// Generated by alef. Do not edit by hand.
// alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc

package dev.kreuzberg

object EmbeddingBackendBridge {
    private val registered = mutableMapOf<String, IEmbeddingBackend>()

    fun register(impl: IEmbeddingBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterEmbeddingBackend(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterEmbeddingBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearEmbeddingBackends()
    }

    fun getAll(): Map<String, IEmbeddingBackend> = registered.toMap()
}
