// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Request parameters for LLM-based structured extraction.
 */
data class ExtractStructuredParams(
    val path: String,
    val schema: String,
    val model: String,
    val schemaName: String,
    val schemaDescription: String?,
    val prompt: String?,
    val apiKey: String?,
    val strict: Boolean
)
