// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

import java.nio.file.Path

/**
 * kreuzberg-gliner-rs ONNX backend wrapper.
 *
 * Holds an initialised `GLiNER<SpanMode>` behind an `Arc<Mutex<...>>` so the
 * model can be safely shared across async tasks (inference is synchronous and
 * serialised internally by the mutex).
 */
data class GlineBackend(
    val repoId: String,
    val modelPath: java.nio.file.Path,
    val tokenizerPath: java.nio.file.Path,
)
