// Generated by alef. Do not edit by hand.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Image element metadata. */
data class ImageMetadataType(
    /** Image source (URL, data URI, or SVG content) */
    val src: String,
    /** Alternative text from alt attribute */
    val alt: String? = null,
    /** Title attribute */
    val title: String? = null,
    /** Image dimensions as (width, height) if available */
    val dimensions: List<Int>? = null,
    /** Image type classification */
    val imageType: ImageType,
    /** Additional attributes as key-value pairs */
    val attributes: List<List<String>> = emptyList(),
)
