// Generated by alef. Do not edit by hand.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Language detection configuration. */
data class LanguageDetectionConfig(
    /** Enable language detection */
    val enabled: Boolean = true,
    /** Minimum confidence threshold (0.0-1.0) */
    val minConfidence: Double = 0.8,
    /** Detect multiple languages in the document */
    val detectMultiple: Boolean = false,
)
