// Generated by alef. Do not edit by hand.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Link element metadata. */
data class LinkMetadata(
    /** The href URL value */
    val href: String,
    /** Link text content (normalized) */
    val text: String,
    /** Optional title attribute */
    val title: String? = null,
    /** Link type classification */
    val linkType: LinkType,
    /** Rel attribute values */
    val rel: List<String> = emptyList(),
    /** Additional attributes as key-value pairs */
    val attributes: List<List<String>> = emptyList(),
)
