// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Model manifest response.
 */
data class ManifestResponse(
    val kreuzbergVersion: String,
    val totalSizeBytes: Long,
    val modelCount: Long,
    val models: List<ManifestEntryResponse>
)
