// Generated by alef. Do not edit by hand.
// alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25

package dev.kreuzberg

import import java.nio.file.Path
/// Bridge adapter for IOcrBackend implementations.
///
/// Wraps a user-supplied IOcrBackend instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class OcrBackendAdapter(private val impl: IOcrBackend) : IOcrBackend {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override suspend fun processImage(imageBytes: ByteArray, config: OcrConfig): ExtractionResult {
        return impl.processImage(imageBytes, config)
    }

    override suspend fun processImageFile(path: java.nio.file.Path, config: OcrConfig): ExtractionResult {
        return impl.processImageFile(path, config)
    }

    override fun supportsLanguage(lang: String): Boolean {
        return impl.supportsLanguage(lang)
    }

    override fun backendType(): OcrBackendType {
        return impl.backendType()
    }

    override fun supportedLanguages(): List<String> {
        return impl.supportedLanguages()
    }

    override fun supportsTableDetection(): Boolean {
        return impl.supportsTableDetection()
    }

    override fun supportsDocumentProcessing(): Boolean {
        return impl.supportsDocumentProcessing()
    }

    override suspend fun processDocument(path: java.nio.file.Path, config: OcrConfig): ExtractionResult {
        return impl.processDocument(path, config)
    }


}
