// Generated by alef. Do not edit by hand.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** One redaction event: which span was rewritten, why, and with what. */
data class RedactionFinding(
    /** Byte-offset start in the original (pre-redaction) `ExtractionResult.content`. */
    val start: Int,
    /** Byte-offset end (exclusive) in the original `ExtractionResult.content`. */
    val end: Int,
    /** PII category that fired this redaction. */
    val category: PiiCategory,
    /** Strategy applied to this finding (mask, hash, token-replace, drop). */
    val strategy: RedactionStrategy,
    /**
     * String that replaced the original mention. Always present; for `Drop` the
     * replacement is the empty string.
     */
    val replacementToken: String,
)
