// Generated by alef. Do not edit by hand.
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad

package dev.kreuzberg

/// Bridge adapter for IRenderer implementations.
///
/// Wraps a user-supplied IRenderer instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class RendererAdapter(private val impl: IRenderer) : IRenderer {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()


}
