// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * A single style definition parsed from `<w:style>` in `word/styles.xml`.
 */
data class StyleDefinition(
    val id: String,
    val name: String?,
    val styleType: String,
    val basedOn: String?,
    val nextStyle: String?,
    val isDefault: Boolean,
    val paragraphProperties: String,
    val runProperties: String
)
