// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Application properties from docProps/app.xml for XLSX
 *
 * Contains Excel-specific document metadata.
 */
data class XlsxAppProperties(
    val application: String?,
    val appVersion: String?,
    val docSecurity: Int?,
    val scaleCrop: Boolean?,
    val linksUpToDate: Boolean?,
    val sharedDoc: Boolean?,
    val hyperlinksChanged: Boolean?,
    val company: String?,
    val worksheetNames: List<String>
)
