// Generated by alef. Do not edit by hand.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * Application properties from docProps/app.xml for XLSX
 *
 * Contains Excel-specific document metadata.
 */
data class XlsxAppProperties(
    /** Application name (e.g., "Microsoft Excel") */
    val application: String? = null,
    /** Application version */
    val appVersion: String? = null,
    /** Document security level */
    val docSecurity: Int? = null,
    /** Scale crop flag */
    val scaleCrop: Boolean? = null,
    /** Links up to date flag */
    val linksUpToDate: Boolean? = null,
    /** Shared document flag */
    val sharedDoc: Boolean? = null,
    /** Hyperlinks changed flag */
    val hyperlinksChanged: Boolean? = null,
    /** Company name */
    val company: String? = null,
    /** Worksheet names */
    val worksheetNames: List<String> = emptyList(),
)
