// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: document_extractor_management.
final class DocumentExtractorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testDocumentExtractorsClear() throws {
        // Clear all document extractors and verify list is empty
        let result = try Kreuzberg.clearDocumentExtractors()
    }

    func testExtractorsList() throws {
        // List all registered document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

}
