// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6273896884ba65f060a36f6dc60947ad51ac08c53491a8c5dfb24aef9bbf711e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: document_extractor_management.
final class DocumentExtractorManagementTests: XCTestCase {
    func testDocumentExtractorsClear() throws {
        // Clear all document extractors and verify list is empty
        let result = try Kreuzberg.clearDocumentExtractors()
    }

    func testExtractorsList() throws {
        // List all registered document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

}
