// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea6bb795d1b8ecbc705bac2aad9d361f8ee3a0fdbd59fb9fe37170b8feb9b5d4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        let result = try clearEmbeddingBackends()
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try listEmbeddingBackends()
    }

}
