// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a9de246ff0a72092b000e1a396343e940e2328bbf365101fb317624dd0da978
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        let result = try Kreuzberg.clearEmbeddingBackends()
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

}
