// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:89c3d47014ed4416f9e6ab18a3b5128bc3b6259d2c6ecc793b47bec8659739b2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        let result = try Kreuzberg.clearEmbeddingBackends()
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

}
