// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: pdf.
final class PdfTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift_e2e/
            .deletingLastPathComponent() // e2e/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testRenderPdfPageFirst() throws {
        // render_pdf_page_to_png: first page
        let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
        let pdfBytesBytes = Array(pdfBytesData)
        let result = try Kreuzberg.renderPdfPageToPng(pdfBytes: pdfBytesBytes, pageIndex: 0, dpi: nil, password: nil)
        XCTAssertGreaterThanOrEqual(result.count, 100)
    }

    func testRenderPdfPageOutOfRange() throws {
        // render_pdf_page_to_png: page out of range
        do {
            let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
            let pdfBytesBytes = Array(pdfBytesData)
            _ = try Kreuzberg.renderPdfPageToPng(pdfBytes: pdfBytesBytes, pageIndex: 999, dpi: nil, password: nil)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
