// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e307f53342e74cf7a20214a173faecfcb661638a3ada9257dc745cc05733f103
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        let result = try Kreuzberg.clearPostProcessors()
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

}
