// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d7dc7690b9785b1948628889b44fe013a83380ab865b26eba38b3fe7902e36a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    func testListDocumentExtractors() throws {
        // List document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

    func testListOcrBackends() throws {
        // List OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

    func testListPostProcessors() throws {
        // List post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

    func testListRenderers() throws {
        // List renderers
        let result = try Kreuzberg.listRenderers()
    }

    func testListValidators() throws {
        // List validators
        let result = try Kreuzberg.listValidators()
    }

}
