// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testListDocumentExtractors() throws {
        // List document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

    func testListOcrBackends() throws {
        // List OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

    func testListPostProcessors() throws {
        // List post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

    func testListRenderers() throws {
        // List renderers
        let result = try Kreuzberg.listRenderers()
    }

    func testListValidators() throws {
        // List validators
        let result = try Kreuzberg.listValidators()
    }

}
