// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d7dc7690b9785b1948628889b44fe013a83380ab865b26eba38b3fe7902e36a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        let result = try Kreuzberg.clearRenderers()
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try Kreuzberg.listRenderers()
    }

}
