// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b1b8c335e73ba0bd93d1bc13b03bbcb5dc11754ee00835a8ebf5887e1ff6998
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        let result = try clearRenderers()
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try listRenderers()
    }

}
