// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bf8fc62d4592f607c649912d3ba7bb5d506fc5c337bdf66bf1799797d30c4710
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        let result = try Kreuzberg.clearValidators()
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Kreuzberg.listValidators()
    }

}
