// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a7b77c67593bd372c7db337f9fd273c8e7daec3aaf6a8a4c8a969f7c966a46f4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Archive (ZIP/TAR/7Z) metadata.
///
/// Extracted from compressed archive files containing file lists and size information.
/// </summary>
public sealed class ArchiveMetadata
{
    /// <summary>
    /// Archive format ("ZIP", "TAR", "7Z", etc.)
    /// </summary>
    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    /// <summary>
    /// Total number of files in the archive
    /// </summary>
    [JsonPropertyName("file_count")]
    public ulong FileCount { get; set; } = 0;

    /// <summary>
    /// Typed entries with path, size, and is_dir fields
    /// </summary>
    [JsonPropertyName("entries")]
    public List<ArchiveFileEntry> Entries { get; set; } = [];

    /// <summary>
    /// Total uncompressed size in bytes
    /// </summary>
    [JsonPropertyName("total_size")]
    public ulong TotalSize { get; set; } = 0;

    /// <summary>
    /// Compressed size in bytes (if available)
    /// </summary>
    [JsonPropertyName("compressed_size")]
    public ulong? CompressedSize { get; set; } = null;

}
