// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:62689e8d9d74d3fc5cb200a14ebbf3ef25bfccac0f5098aa6dba06d425c3d022
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single entry in an archive (file or directory).
/// </summary>
public sealed class ArchiveFileEntry
{
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    [JsonPropertyName("size")]
    public ulong Size { get; set; } = 0;

    [JsonPropertyName("is_dir")]
    public bool IsDir { get; set; } = false;

}
