// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37c06b928e14f8b6cba74796727f78a084803d0d6599f2f54d4975069d082bb7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Chunk request with text and configuration.
/// </summary>
public sealed class ChunkRequest
{
    /// <summary>
    /// Text to chunk (must not be empty)
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Optional chunking configuration
    /// </summary>
    [JsonPropertyName("config")]
    public string? Config { get; set; } = null;

    /// <summary>
    /// Chunker type (text, markdown, yaml, or semantic)
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public string ChunkerType { get; set; } = "";

}
