// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3539bffd5614d3442101ee7da00786f05130075d095ec80e93de14bc611dfb8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Content rendering mode for code extraction.
///
/// Controls how extracted code content is represented in the `content` field
/// of `ExtractionResult`.
/// </summary>
public enum CodeContentMode
{
    /// <summary>
    /// Use TSLP semantic chunks as content (default).
    /// </summary>
    [JsonPropertyName("chunks")]
    Chunks,
    /// <summary>
    /// Use raw source code as content.
    /// </summary>
    [JsonPropertyName("raw")]
    Raw,
    /// <summary>
    /// Emit function/class headings + docstrings (no code bodies).
    /// </summary>
    [JsonPropertyName("structure")]
    Structure,
}
