// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:32de5ea05fb0ab77866f82a4d572fbec59b4f98dde90fc40bdf03983b6b266b1
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Content layer classification for document nodes./// /// Replaces separate body/furniture arrays with per-node granularity./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ContentLayer
{/// <summary>    /// Main document body content.    /// </summary>
[JsonPropertyName("body")]
    Body,/// <summary>    /// Page/section header (running header).    /// </summary>
[JsonPropertyName("header")]
    Header,/// <summary>    /// Page/section footer (running footer).    /// </summary>
[JsonPropertyName("footer")]
    Footer,/// <summary>    /// Footnote content.    /// </summary>
[JsonPropertyName("footnote")]
    Footnote,}
