// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE (DBF) file metadata.
/// </summary>
public sealed record DbfMetadata
{
    /// <summary>
    /// Total number of data records in the DBF file.
    /// </summary>
    [JsonPropertyName("record_count")]
    public ulong RecordCount { get; init; } = 0;

    /// <summary>
    /// Number of field (column) definitions.
    /// </summary>
    [JsonPropertyName("field_count")]
    public ulong FieldCount { get; init; } = 0;

    /// <summary>
    /// Descriptor for each field in the table schema.
    /// </summary>
    [JsonPropertyName("fields")]
    public List<DbfFieldInfo> Fields { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="DbfMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DbfMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DbfMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DbfMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DbfMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
