// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:06fbf9f97f9802a0f57b986021fe3c5536a32e42310b38007bc0d7a8db625e8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for LLM-based structured extraction.
/// </summary>
public sealed class ExtractStructuredParams
{
    /// <summary>
    /// File path to extract from
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// JSON schema for structured output
    /// </summary>
    [JsonPropertyName("schema")]
    public object Schema { get; set; } = "";

    /// <summary>
    /// LLM model (e.g., "openai/gpt-4o")
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    /// <summary>
    /// Schema name (default: "extraction")
    /// </summary>
    [JsonPropertyName("schema_name")]
    public string SchemaName { get; set; } = "";

    /// <summary>
    /// Schema description for the LLM
    /// </summary>
    [JsonPropertyName("schema_description")]
    public string? SchemaDescription { get; set; } = null;

    /// <summary>
    /// Custom Jinja2 prompt template
    /// </summary>
    [JsonPropertyName("prompt")]
    public string? Prompt { get; set; } = null;

    /// <summary>
    /// API key (optional, falls back to env)
    /// </summary>
    [JsonPropertyName("api_key")]
    public string? ApiKey { get; set; } = null;

    /// <summary>
    /// Enable strict mode
    /// </summary>
    [JsonPropertyName("strict")]
    public bool Strict { get; set; } = false;

}
