// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1fe88eb8e33d018da2ba39a58ff3a25da7d9fa2b878acdc709c06597ee1dd6ef
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// How the extracted text was produced.
/// </summary>
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native,
    [JsonPropertyName("ocr")]
    Ocr,
    [JsonPropertyName("mixed")]
    Mixed,
}
