// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:560822708db9734472f1a852732b0b037e04083b4ad1d3eb5d4f2d2e9bc5a3be
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
