// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
