// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea77724b9e6749ddc05b174d4540d268a68ef4be7a18467a9ba1214d51b95682
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
