// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:360525d1e9ef6d2320717f72c1e097ded77ebfe1a3490eb8ff5d6003529332b4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// The 17 canonical document layout classes.
///
/// All model backends (RT-DETR, YOLO, etc.) map their native class IDs
/// to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)
/// map to the closest equivalent.
/// </summary>
public enum LayoutClass
{
    [JsonPropertyName("caption")]
    Caption,
    [JsonPropertyName("footnote")]
    Footnote,
    [JsonPropertyName("formula")]
    Formula,
    [JsonPropertyName("listitem")]
    ListItem,
    [JsonPropertyName("pagefooter")]
    PageFooter,
    [JsonPropertyName("pageheader")]
    PageHeader,
    [JsonPropertyName("picture")]
    Picture,
    [JsonPropertyName("sectionheader")]
    SectionHeader,
    [JsonPropertyName("table")]
    Table,
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("title")]
    Title,
    [JsonPropertyName("documentindex")]
    DocumentIndex,
    [JsonPropertyName("code")]
    Code,
    [JsonPropertyName("checkboxselected")]
    CheckboxSelected,
    [JsonPropertyName("checkboxunselected")]
    CheckboxUnselected,
    [JsonPropertyName("form")]
    Form,
    [JsonPropertyName("keyvalueregion")]
    KeyValueRegion,
}
