// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7aea7d55f2691014e98e6e08f16f72a603bfc03cbf1aa80752c3b408e50aeb65
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Link type classification./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{/// <summary>    /// Anchor link (#section)    /// </summary>
[JsonPropertyName("anchor")]
    Anchor,/// <summary>    /// Internal link (same domain)    /// </summary>
[JsonPropertyName("internal")]
    Internal,/// <summary>    /// External link (different domain)    /// </summary>
[JsonPropertyName("external")]
    External,/// <summary>    /// Email link (mailto:)    /// </summary>
[JsonPropertyName("email")]
    Email,/// <summary>    /// Phone link (tel:)    /// </summary>
[JsonPropertyName("phone")]
    Phone,/// <summary>    /// Other link type    /// </summary>
[JsonPropertyName("other")]
    Other,}
