// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:85cb87a30d2ae82b97dbf0d4d6c68b38ef89f28d22d906412c1b4e9703f847df
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
