// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
