// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1f431b0a4b6e0782e77aa30a3c3ba39c1e8a4ad47bf34db83ead173bcc11dcb3
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
