// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc2ad19d9404b7d04f2f0e80f186f50f36f885674f54931133f9c6ebdf51c04e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Tagged enum for node content. Each variant carries only type-specific data.
///
/// Uses `#[serde(tag = "node_type")]` to avoid "type" keyword collision in
/// Go/Java/TypeScript bindings.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "node_type")]
public abstract record NodeContent
{
    /// <summary>
    /// Document title.
    /// </summary>
    [JsonDerivedType(typeof(Title), "title")]
    public sealed record Title(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Section heading with level (1-6).
    /// </summary>
    [JsonDerivedType(typeof(Heading), "heading")]
    public sealed record Heading(
        [property: JsonPropertyName("level")] byte Level,
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Body text paragraph.
    /// </summary>
    [JsonDerivedType(typeof(Paragraph), "paragraph")]
    public sealed record Paragraph(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// List container — children are `ListItem` nodes.
    /// </summary>
    [JsonDerivedType(typeof(List), "list")]
    public sealed record List(
        [property: JsonPropertyName("ordered")] bool Ordered
    ) : NodeContent;

    /// <summary>
    /// Individual list item.
    /// </summary>
    [JsonDerivedType(typeof(ListItem), "list_item")]
    public sealed record ListItem(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Table with structured cell grid.
    /// </summary>
    [JsonDerivedType(typeof(Table), "table")]
    public sealed record Table(
        [property: JsonPropertyName("grid")] TableGrid Grid
    ) : NodeContent;

    /// <summary>
    /// Image reference.
    /// </summary>
    [JsonDerivedType(typeof(Image), "image")]
    public sealed record Image(
        [property: JsonPropertyName("description")] string? Description,
        [property: JsonPropertyName("image_index")] uint? ImageIndex,
        [property: JsonPropertyName("src")] string? Src
    ) : NodeContent;

    /// <summary>
    /// Code block.
    /// </summary>
    [JsonDerivedType(typeof(Code), "code")]
    public sealed record Code(
        [property: JsonPropertyName("text")] string Text,
        [property: JsonPropertyName("language")] string? Language
    ) : NodeContent;

    /// <summary>
    /// Block quote — container, children carry the quoted content.
    /// </summary>
    [JsonDerivedType(typeof(Quote), "quote")]
    public sealed record Quote() : NodeContent;

    /// <summary>
    /// Mathematical formula / equation.
    /// </summary>
    [JsonDerivedType(typeof(Formula), "formula")]
    public sealed record Formula(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Footnote reference content.
    /// </summary>
    [JsonDerivedType(typeof(Footnote), "footnote")]
    public sealed record Footnote(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Logical grouping container (section, key-value area).
    ///
    /// `heading_level` + `heading_text` capture the section heading directly
    /// rather than relying on a first-child positional convention.
    /// </summary>
    [JsonDerivedType(typeof(Group), "group")]
    public sealed record Group(
        [property: JsonPropertyName("label")] string? Label,
        [property: JsonPropertyName("heading_level")] byte? HeadingLevel,
        [property: JsonPropertyName("heading_text")] string? HeadingText
    ) : NodeContent;

    /// <summary>
    /// Page break marker.
    /// </summary>
    [JsonDerivedType(typeof(PageBreak), "page_break")]
    public sealed record PageBreak() : NodeContent;

    /// <summary>
    /// Presentation slide container — children are the slide's content nodes.
    /// </summary>
    [JsonDerivedType(typeof(Slide), "slide")]
    public sealed record Slide(
        [property: JsonPropertyName("number")] uint Number,
        [property: JsonPropertyName("title")] string? Value
    ) : NodeContent;

    /// <summary>
    /// Definition list container — children are `DefinitionItem` nodes.
    /// </summary>
    [JsonDerivedType(typeof(DefinitionList), "definition_list")]
    public sealed record DefinitionList() : NodeContent;

    /// <summary>
    /// Individual definition list entry with term and definition.
    /// </summary>
    [JsonDerivedType(typeof(DefinitionItem), "definition_item")]
    public sealed record DefinitionItem(
        [property: JsonPropertyName("term")] string Term,
        [property: JsonPropertyName("definition")] string Definition
    ) : NodeContent;

    /// <summary>
    /// Citation or bibliographic reference.
    /// </summary>
    [JsonDerivedType(typeof(Citation), "citation")]
    public sealed record Citation(
        [property: JsonPropertyName("key")] string Key,
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// Admonition / callout container (note, warning, tip, etc.).
    ///
    /// Children carry the admonition body content.
    /// </summary>
    [JsonDerivedType(typeof(Admonition), "admonition")]
    public sealed record Admonition(
        [property: JsonPropertyName("kind")] string Kind,
        [property: JsonPropertyName("title")] string? Value
    ) : NodeContent;

    /// <summary>
    /// Raw block preserved verbatim from the source format.
    ///
    /// Used for content that cannot be mapped to a semantic node type
    /// (e.g. JSX in MDX, raw LaTeX in markdown, embedded HTML).
    /// </summary>
    [JsonDerivedType(typeof(RawBlock), "raw_block")]
    public sealed record RawBlock(
        [property: JsonPropertyName("format")] string Format,
        [property: JsonPropertyName("content")] string Content
    ) : NodeContent;

    /// <summary>
    /// Structured metadata block (email headers, YAML frontmatter, etc.).
    /// </summary>
    [JsonDerivedType(typeof(MetadataBlock), "metadata_block")]
    public sealed record MetadataBlock(
        [property: JsonPropertyName("entries")] List<string> Entries
    ) : NodeContent;

}
