// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7f79530b871d4dd2c49ccddada7cf991e33005d1287ec6d2bc719267f6cca99f
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Hierarchical level of an OCR element./// /// Maps to Tesseract's page segmentation hierarchy and provides/// equivalent semantics for PaddleOCR./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrElementLevel
{/// <summary>    /// Individual word    /// </summary>
[JsonPropertyName("word")]
    Word,/// <summary>    /// Line of text (default for PaddleOCR)    /// </summary>
[JsonPropertyName("line")]
    Line,/// <summary>    /// Paragraph or text block    /// </summary>
[JsonPropertyName("block")]
    Block,/// <summary>    /// Page-level element    /// </summary>
[JsonPropertyName("page")]
    Page,}
