// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7be7261a4236ea1c766ad3429de9c3848d7bcf6a75bf4b822074fedf1fed8668
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
