// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c0ac781c089a3bd14bad00a55c02e1c33e7a87dbd17161f99419c659c278bebd
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
