// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cfc01ee2df96294969c3bb5078bc092434999e9e4620121c91974af9e41d1ff6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Bounding box for an OCR-detected table in pixel coordinates.
/// </summary>
public sealed class OcrTableBoundingBox
{
    /// <summary>
    /// Left x-coordinate (pixels)
    /// </summary>
    [JsonPropertyName("left")]
    public uint Left { get; set; } = 0;

    /// <summary>
    /// Top y-coordinate (pixels)
    /// </summary>
    [JsonPropertyName("top")]
    public uint Top { get; set; } = 0;

    /// <summary>
    /// Right x-coordinate (pixels)
    /// </summary>
    [JsonPropertyName("right")]
    public uint Right { get; set; } = 0;

    /// <summary>
    /// Bottom y-coordinate (pixels)
    /// </summary>
    [JsonPropertyName("bottom")]
    public uint Bottom { get; set; } = 0;

}
