// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7cff49613fd1dbc17423be6ef69dff545bb1046bf6ea4d425b2ea08063742c4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Type of paginated unit in a document.
///
/// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
/// </summary>
public enum PageUnitType
{
    /// <summary>
    /// Standard document pages (PDF, DOCX, images)
    /// </summary>
    [JsonPropertyName("page")]
    Page,
    /// <summary>
    /// Presentation slides (PPTX, ODP)
    /// </summary>
    [JsonPropertyName("slide")]
    Slide,
    /// <summary>
    /// Spreadsheet sheets (XLSX, ODS)
    /// </summary>
    [JsonPropertyName("sheet")]
    Sheet,
}
