// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
