// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e4ef4738606745ea7a0e2959504072747caf240a4073a7cc4a7121b93d587623
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
