// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bbdf563ae605c616cc616c2e462cbc68cf85ed436cdd7271119a609ee60c0df6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Fully resolved (flattened) style after walking the inheritance chain.
/// </summary>
public sealed class ResolvedStyle
{
    [JsonPropertyName("paragraph_properties")]
    public string ParagraphProperties { get; set; } = "";

    [JsonPropertyName("run_properties")]
    public string RunProperties { get; set; } = "";

}
