// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0a3a25cbc419d41233de8e7a8ca7de575cb0d1b0a040921d89d3735b3c03da9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Fully resolved (flattened) style after walking the inheritance chain.
/// </summary>
public sealed class ResolvedStyle
{
    [JsonPropertyName("paragraph_properties")]
    public string ParagraphProperties { get; set; } = "";

    [JsonPropertyName("run_properties")]
    public string RunProperties { get; set; } = "";

}
