// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a77f2ab4f1e90fa3e5edbc161399a3f093faf4c0e72710d0e6f5486b8cdf4f95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Result-shape selection for extraction results.
///
/// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,
/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content
/// blob vs. an element-based decomposition.
/// </summary>
public enum ResultFormat
{
    /// <summary>
    /// Unified format with all content in `content` field
    /// </summary>
    [JsonPropertyName("unified")]
    Unified,
    /// <summary>
    /// Element-based format with semantic element extraction
    /// </summary>
    [JsonPropertyName("element_based")]
    ElementBased,
}
