// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
