// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Structured data (Schema.org, microdata, RDFa) block.
/// </summary>
public sealed record StructuredData
{
    /// <summary>
    /// Type of structured data
    /// </summary>
    [JsonConverter(typeof(StructuredDataTypeJsonConverter))]
    [JsonPropertyName("data_type")]
    public required StructuredDataType DataType { get; init; }

    /// <summary>
    /// Raw JSON string representation
    /// </summary>
    [JsonPropertyName("raw_json")]
    public required string RawJson { get; init; }

    /// <summary>
    /// Schema type if detectable (e.g., "Article", "Event", "Product")
    /// </summary>
    [JsonPropertyName("schema_type")]
    public string? SchemaType { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="StructuredData"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static StructuredData FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<StructuredData>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse StructuredData from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse StructuredData from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
