// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:19f16c654f4b244751706814bccb74705d8479a20017311b875cd5efc1386e18
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Structured data (Schema.org, microdata, RDFa) block.
/// </summary>
public sealed class StructuredData
{
    /// <summary>
    /// Type of structured data
    /// </summary>
    [JsonConverter(typeof(StructuredDataTypeJsonConverter))]
    [JsonPropertyName("data_type")]
    public StructuredDataType DataType { get; set; } = default!;

    /// <summary>
    /// Raw JSON string representation
    /// </summary>
    [JsonPropertyName("raw_json")]
    public string RawJson { get; set; } = "";

    /// <summary>
    /// Schema type if detectable (e.g., "Article", "Event", "Product")
    /// </summary>
    [JsonPropertyName("schema_type")]
    public string? SchemaType { get; set; } = null;

}
