// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b5c16853b7141391e1d97e35585d8f806875d9519e40a8a45fadf12cf93bf49e
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
