// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:12ae8882805b91cd49dd1d37ed8589052b64c8ce99363ea70fed53bdf2619f15
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
