// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:332e5f2a95b7fd24e54959ed460c7b548291ccb6709a28f3737acaa5b68a2127
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// YAKE-specific parameters.
/// </summary>
public sealed class YakeParams
{
    /// <summary>
    /// Window size for co-occurrence analysis (default: 2).
    ///
    /// Controls the context window for computing co-occurrence statistics.
    /// </summary>
    [JsonPropertyName("window_size")]
    public ulong WindowSize { get; set; } = 2;

}
