/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RerankerBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  rerank?(query: string, documents: string): string;
}

export class RerankerBackendAdapter {
  constructor(private bridge: RerankerBackendBridge) {}

  async rerank(query: string, documents: string): Promise<string> {
    try {
      const result = await this.bridge.rerank(query, documents);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
