# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c902419f33b8d37dca3ee9255b3fc5d31587da5c5903257e9dc1bc3c170c4a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

# Resolve fixture paths against the repo's `test_documents/` directory.
# testthat sources setup-*.R with the working directory at tests/,
# so test_documents lives three directories up: tests/ -> e2e/r/ -> e2e/ -> repo root.
# Each `test_that()` block has its working directory reset back to tests/, so
# fixture lookups must be performed via this helper rather than relying on `setwd`.
.kreuzberg_test_documents <- normalizePath("../../../test_documents", mustWork = FALSE)
.resolve_fixture <- function(path) {
  if (dir.exists(.kreuzberg_test_documents)) {
    file.path(.kreuzberg_test_documents, path)
  } else {
    path
  }
}
