# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  invisible(clear_embedding_backends())
  expect_true(TRUE)
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
