# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b60d21809cc6ff3c11a5d6b4ccb1723b6ca7a200e0abe0624f5be5eb98bf1007
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends()
  expect_true(TRUE)
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})

test_that("list_validators: List validators", {
  result <- list_validators()
  expect_true(TRUE)
})
