# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d42f46e55982be71e05fac4c6d84c129ac5aa99799c090ff9579d47eb3f37b2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: async

test_that("async_extract_bytes_empty_mime: extract_bytes empty MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "", config = ExtractionConfig$default()))
})

test_that("async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "application/x-nonexistent", config = ExtractionConfig$default()))
})
