# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8d7dc7690b9785b1948628889b44fe013a83380ab865b26eba38b3fe7902e36a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  invisible(clear_document_extractors())
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})
