# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2552bd506c5f3b07bacdfa6cc8d5dcd97d706d28ed34298a4678c069d6254c7b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management

test_that("renderers_clear: Clear all renderers and verify list is empty", {
  invisible(clear_renderers())
  expect_true(TRUE)
})

test_that("renderers_list: List all registered renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})
