# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})

test_that("list_embedding_backends: List embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends()
  expect_true(TRUE)
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})

test_that("list_renderers: List renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})

test_that("list_validators: List validators", {
  result <- list_validators()
  expect_true(TRUE)
})
