// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:025fa3f03c2fc309fcbef6bbf9965a30499993203f41ec5c37205f58dc663b4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: error

test "error_empty_bytes" {
    // Graceful handling of empty bytes (should not error)
    const result = kreuzberg.extract_bytes_sync("text/empty.txt", "text/plain");
}

test "error_empty_mime" {
    // Error when extracting with empty MIME type
    const result = kreuzberg.extract_bytes_sync("text/plain.txt", "") catch |err| {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    // Perform success assertions if any
}

test "error_extract_bytes_conflicting_ocr" {
    // extract_bytes force+disable OCR
    const result = kreuzberg.extract_bytes_sync("text/fake_text.txt", "text/plain", "{\"disable_ocr\":true,\"force_ocr\":true}") catch |err| {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    // Perform success assertions if any
}

test "error_invalid_mime_format" {
    // Error when extracting with invalid MIME type format
    const result = kreuzberg.extract_bytes_sync("text/plain.txt", "not-a-mime") catch |err| {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    // Perform success assertions if any
}

test "error_unsupported_mime" {
    // Error when extracting with unsupported MIME type
    const result = kreuzberg.extract_bytes_sync("text/plain.txt", "application/x-nonexistent") catch |err| {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    // Perform success assertions if any
}
