// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: ocr_backend_management

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    suppress_abort();
    _ = try kreuzberg.clear_ocr_backends();
}

test "ocr_backends_list" {
    // List all registered OCR backends
    suppress_abort();
    _ = try kreuzberg.list_ocr_backends();
}

test "ocr_backends_unregister" {
    // Unregister nonexistent OCR backend gracefully
    suppress_abort();
    _ = try kreuzberg.unregister_ocr_backend("nonexistent-backend-xyz");
}
