// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:00652faa6ffe5ecb7a76d9690572eefa9dafc9c3d1a45869ee0df14f0fca0fec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: pdf

test "render_pdf_page_first" {
    // render_pdf_page_to_png: first page
    const pdf_bytes_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "pdf/fake_memo.pdf", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(pdf_bytes_bytes);
    const result = try kreuzberg.render_pdf_page_to_png(pdf_bytes_bytes, 0, null, null);
    try testing.expect(result.len >= 100);
}

test "render_pdf_page_out_of_range" {
    // render_pdf_page_to_png: page out of range
    const pdf_bytes_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "pdf/fake_memo.pdf", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(pdf_bytes_bytes);
    const result = kreuzberg.render_pdf_page_to_png(pdf_bytes_bytes, 999, null, null) catch {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    _ = result;
}
