// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0cbaeda88d276e601c589a8eb2d8396209b9dc1a968243e826f20c1695edbcc9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: registry_operations

test "extensions_docx" {
    // Get file extensions for DOCX MIME type
    const result = kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}

test "extensions_html" {
    // Get file extensions for HTML MIME type
    const result = kreuzberg.get_extensions_for_mime("text/html");
}

test "extensions_pdf" {
    // Get file extensions for PDF MIME type
    const result = kreuzberg.get_extensions_for_mime("application/pdf");
    try testing.expect(std.mem.indexOf(u8, result, "pdf") != null);
}
