// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: registry_operations

test "extensions_docx" {
    // Get file extensions for DOCX MIME type
    suppress_abort();
    _ = try kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}

test "extensions_html" {
    // Get file extensions for HTML MIME type
    suppress_abort();
    _ = try kreuzberg.get_extensions_for_mime("text/html");
}

test "extensions_pdf" {
    // Get file extensions for PDF MIME type
    suppress_abort();
    _ = try kreuzberg.get_extensions_for_mime("application/pdf");
}
