// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:04546147555fb62a6e008e92107b3b5193bfbfb91f11a7dec869bc1a87301c1f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: renderer_management

test "renderers_clear" {
    // Clear all renderers and verify list is empty
    _ = try kreuzberg.clear_renderers();
}

test "renderers_list" {
    // List all registered renderers
    _ = try kreuzberg.list_renderers();
}
