// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:25a390ad25f14bf39ce460646df2ea8ba748eb90c3841bccabd437c415d949d7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {

    @Test
    void testEmbeddingBackendsClear() throws Exception {
        // Clear all embedding backends and verify list is empty
        var result = Kreuzberg.clearEmbeddingBackends();

    }


    @Test
    void testEmbeddingBackendsList() throws Exception {
        // List all registered embedding backends
        var result = Kreuzberg.listEmbeddingBackends();

    }

}
