// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d7dc7690b9785b1948628889b44fe013a83380ab865b26eba38b3fe7902e36a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {

    @Test
    void testEmbeddingBackendsClear() throws Exception {
        // Clear all embedding backends and verify list is empty
        Kreuzberg.clearEmbeddingBackends();

    }


    @Test
    void testEmbeddingBackendsList() throws Exception {
        // List all registered embedding backends
        var result = Kreuzberg.listEmbeddingBackends();

    }

}
