// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: embedding_backend_management. */
public class EmbeddingBackendManagementTest {

    @Test
    void testEmbeddingBackendsClear() throws Exception {
        // Clear all embedding backends and verify list is empty
        Kreuzberg.clearEmbeddingBackends();


    }


    @Test
    void testEmbeddingBackendsList() throws Exception {
        // List all registered embedding backends
        var result = Kreuzberg.listEmbeddingBackends();


    }

}
