// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6a42f7eb0c4cfd72ea4c7f112a7315e12d7f9ca3c1629b12bd11cacec8ab1b12
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: ocr_backend_management. */
class OcrBackendManagementTest {

    @Test
    void testOcrBackendsClear() throws Exception {
        // Clear all OCR backends and verify list is empty
        Kreuzberg.clearOcrBackends();

    }


    @Test
    void testOcrBackendsList() throws Exception {
        // List all registered OCR backends
        var result = Kreuzberg.listOcrBackends();

    }


    @Test
    void testOcrBackendsUnregister() throws Exception {
        // Unregister nonexistent OCR backend gracefully
        var result = Kreuzberg.unregisterOcrBackend("nonexistent-backend-xyz");

    }

}
