# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4cfa77592d7ed9a60113baacdacad0367c959db477396f9fc39a7d250d7fc057
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.1'
end
