// DO NOT EDIT - auto-generated by alef
// alef:hash:3513fad1ecefd2f754414f46a7aca18e6dd796f7266d54bd7fae22b6fc6c321e
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
