// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ad0d3ae0c5cb88ff413288f39eadf26ab7c42901b8b9ea6a7ad9da26cb663a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings("checkstyle:LineLength")
public class ConversionErrorException extends KreuzbergRsException {
    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
