// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A resolved relationship between two nodes in the document tree.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocumentRelationship.Builder.class)
@SuppressWarnings("PMD")
public record DocumentRelationship(
    @JsonProperty("source") int source,
    @JsonProperty("target") int target,
    @JsonProperty("kind") RelationshipKind kind
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private int source = 0;
private int target = 0;
private RelationshipKind kind = null;

        /** Sets the source field. */
        @JsonProperty("source")
        public Builder withSource(final int value) {
            this.source = value;
            return this;
        }

        /** Sets the target field. */
        @JsonProperty("target")
        public Builder withTarget(final int value) {
            this.target = value;
            return this;
        }

        /** Sets the kind field. */
        @JsonProperty("kind")
        public Builder withKind(final RelationshipKind value) {
            this.kind = value;
            return this;
        }

        /** Builds the DocumentRelationship instance. */
        public DocumentRelationship build() {
            return new DocumentRelationship(
                source,
                target,
                kind
            );
        }
    }
    // CPD-ON
}
