// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Image metadata extracted from image files.
 *
 * Includes dimensions, format, and EXIF data.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageMetadata.Builder.class)
@SuppressWarnings("PMD")
public record ImageMetadata(
    @JsonProperty("width") int width,
    @JsonProperty("height") int height,
    @JsonProperty("format") String format,
    @JsonProperty("exif") Map<String, String> exif
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private int width = 0;
private int height = 0;
private String format = "";
private Map<String, String> exif = Map.of();

        /** Sets the width field. */
        @JsonProperty("width")
        public Builder withWidth(final int value) {
            this.width = value;
            return this;
        }

        /** Sets the height field. */
        @JsonProperty("height")
        public Builder withHeight(final int value) {
            this.height = value;
            return this;
        }

        /** Sets the format field. */
        @JsonProperty("format")
        public Builder withFormat(final String value) {
            this.format = value;
            return this;
        }

        /** Sets the exif field. */
        @JsonProperty("exif")
        public Builder withExif(final Map<String, String> value) {
            this.exif = value;
            return this;
        }

        /** Builds the ImageMetadata instance. */
        public ImageMetadata build() {
            return new ImageMetadata(
                width,
                height,
                format,
                exif
            );
        }
    }
    // CPD-ON
}
