// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Types of inline elements in Djot.
 */
public enum InlineType {
    Text("text"),
    Strong("strong"),
    Emphasis("emphasis"),
    Highlight("highlight"),
    Subscript("subscript"),
    Superscript("superscript"),
    Insert("insert"),
    Delete("delete"),
    Code("code"),
    Link("link"),
    Image("image"),
    Span("span"),
    Math("math"),
    RawInline("raw_inline"),
    FootnoteRef("footnote_ref"),
    Symbol("symbol");

    /** The string value. */
    private final String value;

    InlineType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static InlineType fromValue(final String value) {
        for (InlineType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
