// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends KreuzbergRsException {
    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
