// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Keyword algorithm selection.
 */
@SuppressWarnings("PMD")
public enum KeywordAlgorithm {
    /**
     * YAKE (Yet Another Keyword Extractor) - statistical approach
     */
    Yake("yake"),
    /**
     * RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
     */
    Rake("rake");


    /** The string value. */
    private final String value;

    KeywordAlgorithm(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static KeywordAlgorithm fromValue(final String value) {
        for (KeywordAlgorithm e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown KeywordAlgorithm value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
