// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of list detection.
 */
@SuppressWarnings("PMD")
public enum ListType {
    /**
     * Bullet points (-, *, •, etc.)
     */
    Bullet("bullet"),
    /**
     * Numbered lists (1., 2., etc.)
     */
    Numbered("numbered"),
    /**
     * Lettered lists (a., b., A., B., etc.)
     */
    Lettered("lettered"),
    /**
     * Indented items
     */
    Indented("indented");


    /** The string value. */
    private final String value;

    ListType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ListType fromValue(final String value) {
        for (ListType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ListType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
