// DO NOT EDIT - auto-generated by alef
// alef:hash:b491b37b2cabb245073709e90463bbb6b52b689692579fb2c4fb0534edd41664
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
