// DO NOT EDIT - auto-generated by alef
// alef:hash:e5870fcbc7db3fc15724bd2a117823560dba3158d4b639d77a03254372d6456b
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
