// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of PDF annotation.
 */
@SuppressWarnings("PMD")
public enum PdfAnnotationType {
    /**
     * Sticky note / text annotation
     */
    Text("text"),
    /**
     * Highlighted text region
     */
    Highlight("highlight"),
    /**
     * Hyperlink annotation
     */
    Link("link"),
    /**
     * Rubber stamp annotation
     */
    Stamp("stamp"),
    /**
     * Underline text markup
     */
    Underline("underline"),
    /**
     * Strikeout text markup
     */
    StrikeOut("strike_out"),
    /**
     * Any other annotation type
     */
    Other("other");


    /** The string value. */
    private final String value;

    PdfAnnotationType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PdfAnnotationType fromValue(final String value) {
        for (PdfAnnotationType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PdfAnnotationType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
