// DO NOT EDIT - auto-generated by alef
// alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
package dev.kreuzberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
