// DO NOT EDIT - auto-generated by alef
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
