# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a20c86236be5d8fe9007afc41cf42acca8237796ac9b302ada6336beb632bbe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Pytest configuration for e2e tests."""

import os
from pathlib import Path

# Ensure the package is importable.
# The kreuzberg package is expected to be installed in the current environment.

# Change to the test_documents directory so that fixture file paths like
# "pdf/fake_memo.pdf" resolve correctly when running pytest from e2e/python/.
_TEST_DOCUMENTS = Path(__file__).parent.parent.parent / "test_documents"
if _TEST_DOCUMENTS.is_dir():
    os.chdir(_TEST_DOCUMENTS)
