# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
import os
from pathlib import Path

# Ensure the package is importable.
# The kreuzberg package is expected to be installed in the current environment.

# Change to the configured test-documents directory so that fixture file
# paths like "pdf/fake_memo.pdf" resolve correctly when running pytest
# from e2e/python/.
_TEST_DOCUMENTS = Path(__file__).parent.parent.parent / "test_documents"
if _TEST_DOCUMENTS.is_dir():
    os.chdir(_TEST_DOCUMENTS)
