# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a15fd0e27801b496b4039f64a99b975983bfb2c78e81d065fd69b2795a64b508
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative "kreuzberg/version"
require_relative "kreuzberg/native"

module Kreuzberg
  # Re-export all types and functions from native extension
end
