# Generated by alef. Do not edit by hand.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
