// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9dfaad2248001da1022c478137966cc58ca74895808b979e215d20aaff75dec9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * OpenAPI documentation structure.
 *
 * Defines all endpoints, request/response schemas, and examples
 * for the Kreuzberg document extraction API.
 */
public class ApiDoc implements AutoCloseable {
    private final MemorySegment handle;

    ApiDoc(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_API_DOC_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free ApiDoc: " + e.getMessage(), e);
            }
        }
    }
}
