// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ed2484969b5f6813fdb94021cd9daa26c1539321f84ef177ce98c43f1c3962d7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A single entry in an archive (file or directory).
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ArchiveFileEntryBuilder {

    private String path = "";
    private long size = 0;
    private boolean isDir = false;

    /** Sets the path field. */
    public ArchiveFileEntryBuilder withPath(final String value) {
        this.path = value;
        return this;
    }

    /** Sets the size field. */
    public ArchiveFileEntryBuilder withSize(final long value) {
        this.size = value;
        return this;
    }

    /** Sets the isDir field. */
    public ArchiveFileEntryBuilder withIsDir(final boolean value) {
        this.isDir = value;
        return this;
    }

    /** Builds the ArchiveFileEntry instance. */
    public ArchiveFileEntry build() {
        return new ArchiveFileEntry(path, size, isDir);
    }
}
