// DO NOT EDIT - auto-generated by alef
// alef:hash:39253b27479670a6e8e5fdd6e011618ed82aa2da0b596b0cc76264926bed0f39
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
