// DO NOT EDIT - auto-generated by alef
// alef:hash:caf7715f0c65ced4821852af0be711df8e8a51d5def7bbcea09dc95260d3b918
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
