// DO NOT EDIT - auto-generated by alef
// alef:hash:b8b847df4f701a4856d2610e6f1510eab94bf72603b7c43c1c63f5300cfee407
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
