// DO NOT EDIT - auto-generated by alef
// alef:hash:cca4cba9ee656de59e0c1b27083f4a40266b5e9eb751ae58e2c75b3fb7a13fba
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
