// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9682b98539ecf2526d6594ad88bee9378b71aefb6c01d74bfbb165957096b22
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown when type conversion fails. */
public class ConversionErrorException extends KreuzbergRsException {
    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
