// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3849e1938fd15e137a9c75dde1ed36d8e10dfb26f19f65a855172df04bdca0f4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectResponse(
        /** Detected MIME type */
        @JsonProperty("mime_type") String mimeType,
        /** Original filename (if provided) */
        @Nullable String filename) {
}
