// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e67256d7f7f4df6907b82c36ff1cc958bbc0c5aa9f111e0ce9e3036fb5bc67eb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A detected structural boundary in the text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectedBoundary(
        /** Byte offset of the start of the line in the original text. */
        @JsonProperty("byte_offset") long byteOffset,
        /** Whether this boundary looks like a header/section title. */
        @JsonProperty("is_header") boolean isHeader) {
}
