// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94ef04874a0558978fc450251b7dd726193347b043423a9685ff9af7bd85620c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Link element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotLink(
    /** Link URL */
    String url,
    /** Link text content */
    String text,
    /** Optional title */
    @Nullable String title,
    /** Element attributes */
    @Nullable String attributes
) {
}
