// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e627f9da699e1c2cdb607f5a414389ead019fc0fde4ede3906b3c3fe4d7bb619
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Link element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotLink(
        /** Link URL */
        String url,
        /** Link text content */
        String text,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
