// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df50aa33ee846159077e2864c4e0612e15d9ceedc6f5e66d3f54a2982266ebf4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorMetadata.Builder.class)
public record ErrorMetadata(@JsonProperty("error_type") String errorType, String message) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("error_type")
        private String errorType = "";
        @JsonProperty("message")
        private String message = "";

        /** Sets the errorType field. */
        @JsonProperty("error_type")
        public Builder withErrorType(final String value) {
            this.errorType = value;
            return this;
        }

        /** Sets the message field. */
        @JsonProperty("message")
        public Builder withMessage(final String value) {
            this.message = value;
            return this;
        }

        /** Builds the ErrorMetadata instance. */
        public ErrorMetadata build() {
            return new ErrorMetadata(
                errorType,
                message
            );
        }
    }
    // CPD-ON
}
