// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8400b260677f31b737bed68a6dfa65c8ffe2c47cd5dd1b279a1cf4f085e7660
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Single Excel worksheet.
 *
 * Represents one sheet from an Excel workbook with its content converted to Markdown format and dimensional statistics.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExcelSheet(
        /** Sheet name as it appears in Excel */
        String name,
        /** Sheet content converted to Markdown tables */
        String markdown,
        /** Number of rows */
        @JsonProperty("row_count") long rowCount,
        /** Number of columns */
        @JsonProperty("col_count") long colCount,
        /** Total number of non-empty cells */
        @JsonProperty("cell_count") long cellCount,
        /** Pre-extracted table cells (2D vector of cell values) */
        @Nullable @JsonProperty("table_cells") List<List<String>> tableCells) {
}
