// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:037dbd9ab9f4fe0cc4cf28781e9542cc402456da5fa098c5eded8f081ad386fb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Single Excel worksheet.
 *
 * Represents one sheet from an Excel workbook with its content
 * converted to Markdown format and dimensional statistics.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExcelSheet(
    /** Sheet name as it appears in Excel */
    String name,
    /** Sheet content converted to Markdown tables */
    String markdown,
    /** Number of rows */
    @JsonProperty("row_count") long rowCount,
    /** Number of columns */
    @JsonProperty("col_count") long colCount,
    /** Total number of non-empty cells */
    @JsonProperty("cell_count") long cellCount,
    /** Pre-extracted table cells (2D vector of cell values) */
    @Nullable @JsonProperty("table_cells") List<List<String>> tableCells
) {
}
