// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77dbfd3e3471adbbdc4a2670db7cd7df88111a91573e90037ee0b0163198773b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * FictionBook (FB2) metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FictionBookMetadataBuilder.class)
public record FictionBookMetadata(@JsonInclude(JsonInclude.Include.NON_NULL) List<String> genres,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> sequences, @Nullable String annotation) {
    public static FictionBookMetadataBuilder builder() {
        return new FictionBookMetadataBuilder();
    }
}
