// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:872e67b1c074e41a7f5fb004b295b2db562709bfea8513fde289c30535f847fd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Header/heading element metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HeaderMetadata(
        /** Header level: 1 (h1) through 6 (h6) */
        byte level,
        /** Normalized text content of the header */
        String text,
        /** HTML id attribute if present */
        @Nullable String id,
        /** Document tree depth at the header element */
        long depth,
        /** Byte offset in original HTML document */
        @JsonProperty("html_offset") long htmlOffset) {
}
