// DO NOT EDIT - auto-generated by alef
// alef:hash:919baa4e06ef9d91a60258a4231e7d385dd130dbf5abfe30a92b76b04aa49837
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
