// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ff0caed1800175a65c516ec7b6a2f5e80785f0ff8c7ade1ca918dba31802d26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Language detection configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LanguageDetectionConfigBuilder.class)
public record LanguageDetectionConfig(
    /** Enable language detection */
    boolean enabled,
    /** Minimum confidence threshold (0.0-1.0) */
    @JsonProperty("min_confidence") double minConfidence,
    /** Detect multiple languages in the document */
    @JsonProperty("detect_multiple") boolean detectMultiple
) {
    public static LanguageDetectionConfigBuilder builder() {
        return new LanguageDetectionConfigBuilder();
    }
}
