// DO NOT EDIT - auto-generated by alef
// alef:hash:0c474bfae9771e214b7756001cee08b46619d0fffe5648d8b94e0094e15ff2ae
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
