// DO NOT EDIT - auto-generated by alef
// alef:hash:c603d94837da42e64fe872b71c01678885e34e53910ec7a02f85a8da821227bd
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
