// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf227fb60dfe7ba033ba215388ab9d4d851ffb3d2421e885d87cc64f59d36df9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Model manifest response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ManifestResponse(
        /** Kreuzberg version */
        @JsonProperty("kreuzberg_version") String kreuzbergVersion,
        /** Total size of all models in bytes */
        @JsonProperty("total_size_bytes") long totalSizeBytes,
        /** Number of models in the manifest */
        @JsonProperty("model_count") long modelCount,
        /** Individual model entries */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<ManifestEntryResponse> models) {
}
