// DO NOT EDIT - auto-generated by alef
// alef:hash:93484f248bf53b10afef1247596ba3c91f7267965b9f8d8a6d000aa50a73b69b
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
