// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ad885f0c0e00e53043ac9842ebc5666259c2af68b969967ca6fe227c15e0a3ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location) from recognition confidence (how
 * confident about the actual text content).
 */
@JsonPOJOBuilder(withPrefix = "with")
public class OcrConfidenceBuilder {

    private Optional<Double> detection = Optional.empty();
    private double recognition = 0.0;

    /** Sets the detection field. */
    public OcrConfidenceBuilder withDetection(final Optional<Double> value) {
        this.detection = value;
        return this;
    }

    /** Sets the recognition field. */
    public OcrConfidenceBuilder withRecognition(final double value) {
        this.recognition = value;
        return this;
    }

    /** Builds the OcrConfidence instance. */
    public OcrConfidence build() {
        return new OcrConfidence(detection.orElse(null), recognition);
    }
}
