// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5cb1e30093726afc7001909da436824f050d0523be620416e8ae933f2cba233b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(builder = OcrCacheStatsBuilder.class)
public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
    public static OcrCacheStatsBuilder builder() {
        return new OcrCacheStatsBuilder();
    }
}
