// DO NOT EDIT - auto-generated by alef
// alef:hash:d8019731bf575d11b84665b1bb1d759fc5772b6bf96a20c2ffb79f5f239ba036
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
