// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:00df922a048e2c6624837b3c74d0775cca06ba4c00455844488bb9c6544d9558
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Document orientation detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OrientationResult(int degrees, float confidence) {
}
