// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:878a103595f3d37a37f7f3ac0239dfc981b121817da41be08859356c5153f2a0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Page extraction and tracking configuration.
 *
 * Controls how pages are extracted, tracked, and represented in the extraction results.
 * When {@code None}, page tracking is disabled.
 *
 * Page range tracking in chunk metadata (first_page/last_page) is automatically enabled
 * when page boundaries are available and chunking is configured.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PageConfigBuilder {

    private boolean extractPages = false;
    private boolean insertPageMarkers = false;
    private String markerFormat = "\n\n<!-- PAGE {page_num} -->\n\n";

    /** Sets the extractPages field. */
    public PageConfigBuilder withExtractPages(final boolean value) {
        this.extractPages = value;
        return this;
    }

    /** Sets the insertPageMarkers field. */
    public PageConfigBuilder withInsertPageMarkers(final boolean value) {
        this.insertPageMarkers = value;
        return this;
    }

    /** Sets the markerFormat field. */
    public PageConfigBuilder withMarkerFormat(final String value) {
        this.markerFormat = value;
        return this;
    }

    /** Builds the PageConfig instance. */
    public PageConfig build() {
        return new PageConfig(
            extractPages,
            insertPageMarkers,
            markerFormat
        );
    }
}
