// DO NOT EDIT - auto-generated by alef
// alef:hash:5fa6d5c3610c5ac5b92ad654b4993ae96d9e0764b14df4cead82351c22ca62f9
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
