// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:949b39f5946b3167587053cfce5f2f2f2eaa14e46f2d1af2e43a70c311e08958
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
@JsonDeserialize(builder = ResolvedStyleBuilder.class)
public record ResolvedStyle(
    @JsonProperty("paragraph_properties") String paragraphProperties,
    @JsonProperty("run_properties") String runProperties
) {
    public static ResolvedStyleBuilder builder() {
        return new ResolvedStyleBuilder();
    }
}
