// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ad6010c02473f039326a9c767f61ccabb4abed3dcb9bf0392f11fd64e9d4b4bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Kreuzberg can process.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SupportedFormat(String extension, @JsonProperty("mime_type") String mimeType) {
}
