// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82ee33cd0bb0fc9b8c93772772c1387d1cebd16a3c5ffeb3b61289dcb7f33e9a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Manages tessdata file downloading, caching, and manifest generation.
 */
public class TessdataManager implements AutoCloseable {
    private final MemorySegment handle;

    TessdataManager(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TESSDATA_MANAGER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TessdataManager: " + e.getMessage(), e);
            }
        }
    }
}
