// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a4a71e0f7142d533e560c07ab005917a467a8f7c0f36704b7bf6825a7786fe9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token reduction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TokenReductionOptionsBuilder {

    @JsonProperty("mode")
    private String mode = "";
    @JsonProperty("preserve_important_words")
    private boolean preserveImportantWords = true;

    /** Sets the mode field. */
    @JsonProperty("mode")
    public TokenReductionOptionsBuilder withMode(final String value) {
        this.mode = value;
        return this;
    }

    /** Sets the preserveImportantWords field. */
    @JsonProperty("preserve_important_words")
    public TokenReductionOptionsBuilder withPreserveImportantWords(final boolean value) {
        this.preserveImportantWords = value;
        return this;
    }

    /** Builds the TokenReductionOptions instance. */
    public TokenReductionOptions build() {
        return new TokenReductionOptions(
            mode,
            preserveImportantWords
        );
    }
}
