// DO NOT EDIT - auto-generated by alef
// alef:hash:8be6e62f74d5d2eb5b0af4a8c69ea16d4f0c2c054c21852481794b20366f0070
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
