// DO NOT EDIT - auto-generated by alef
// alef:hash:4c534e437fcf22adfc03b35e601bf4a8969a146369ca0110daacf56c3de05c70
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
