# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d96fffa497a838452260239a2e61531b6de5c9fb0a80b660d4a0e2a79778854f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnchorProperties do
  @moduledoc "Properties for anchored drawings."

  defstruct behind_doc: false,
            layout_in_cell: false,
            relative_height: 0,
            position_h: "",
            position_v: "",
            wrap_type: ""
end
