# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ebf7378cfadfccd4437ef347c10830650987c0e4b87a568ed3caaff7f11b19f4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
