# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.AudioMetadata do
  @moduledoc """
  Audio/video file metadata.

  Populated from container tags (ID3v2, MP4 atoms, Vorbis comments, etc.) and
  PCM decode properties. Available when the `transcription-types` feature is enabled.
  """

  @typedoc "Audio/video file metadata."
  @type t :: %__MODULE__{
          duration_ms: non_neg_integer() | nil,
          codec: String.t() | nil,
          container: String.t() | nil,
          sample_rate_hz: non_neg_integer() | nil,
          channels: non_neg_integer() | nil,
          bitrate: non_neg_integer() | nil
        }

  defstruct duration_ms: nil,
            codec: nil,
            container: nil,
            sample_rate_hz: nil,
            channels: nil,
            bitrate: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
