# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0489ae8cd8df1c2b9e4a65383464462b5d637dc6cebeb423dcff993e31e8527b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
