# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc """
  Batch item for byte array extraction.

  Used with `batch_extract_bytes` and `batch_extract_bytes_sync`
  to represent a single item in a batch extraction job.
  """

  @typedoc "Batch item for byte array extraction."
  @type t :: %__MODULE__{
          content: binary(),
          mime_type: String.t() | nil,
          config: map() | nil
        }

  defstruct content: <<>>,
            mime_type: nil,
            config: nil
end
