# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6bd8cd2c5cecdb7237da85374ec1f4ae084db298c844c086d5b352db85a10bd8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
