# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchFileItem do
  @moduledoc """
  Batch item for file extraction.

  Used with `batch_extract_files` and `batch_extract_files_sync`
  to represent a single file in a batch extraction job.
  """

  @typedoc "Batch item for file extraction."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          config: map() | nil
        }

  defstruct path: nil,
            config: nil
end
