# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ad55007585e1abcd52bc4ab84e535a75870f167527477b482ef041c98ab6b233
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  defstruct entry_count: 0,
            citation_keys: [],
            authors: [],
            year_range: nil,
            entry_types: %{}
end
