# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21b1616e3415ea17ac129aef83e35e372fc8c25f807310e9e0392f46b970d327
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
