# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CacheStats do
  @moduledoc "Aggregate statistics for a kreuzberg cache directory."

  @typedoc "Aggregate statistics for a kreuzberg cache directory."
  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float(),
          available_space_mb: float(),
          oldest_file_age_days: float(),
          newest_file_age_days: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0,
            available_space_mb: 0.0,
            oldest_file_age_days: 0.0,
            newest_file_age_days: 0.0
end
