# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fee0d71984a73f355f3f83b5e4d0f7791438f3bf44f98a1262810e45182c4dbc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkRequest do
  @moduledoc "Chunk request with text and configuration."

  defstruct text: "",
            config: nil,
            chunker_type: ""
end
