# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e59d455daf970663cb93d2200b959d14d232b986c9b42fdb13dc69e52901281d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
