# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
