# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
