# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fa1e85830cf1e85a6fe4e52dbb2d9f6478f6331452ee5d9829aac8ff10df0ba
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
