# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ContentLayer do
  @moduledoc """
  Content layer classification for document nodes.

  Replaces separate body/furniture arrays with per-node granularity.
  """

  @typedoc "Content layer classification for document nodes."
  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @doc "Main document body content."
  @spec body() :: t()
  def body, do: @body
  @doc "Page/section header (running header)."
  @spec header() :: t()
  def header, do: @header
  @doc "Page/section footer (running footer)."
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Footnote content."
  @spec footnote() :: t()
  def footnote, do: @footnote
end
