# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc2a236ef43d3a0cd6f634d375c18391fd0299e372dacdac701f762c3a90d0ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
