# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7721af73104e3e59378bc666508d33e8a93491b496874875289d136ecc376c97
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentLayer do
  @moduledoc "Content layer classification for document nodes."

  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @spec body() :: t()
  def body, do: @body
  @spec header() :: t()
  def header, do: @header
  @spec footer() :: t()
  def footer, do: @footer
  @spec footnote() :: t()
  def footnote, do: @footnote
end
