# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2c35f93dd25c0a3a0a353566a1d3554fc6d22f7c89a507577725afa83a77831
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
