# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9983f7cc504080dfba913c2e857bbc92321052ff6467a0c1f33483496dde6bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
