# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bafe6b8a04b1add079fc199e92b02d1512f86bf3ce18da9bb481e355241a477b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  defstruct mime_type: "",
            filename: nil
end
