# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a5ef6060f206e110d58507cc42a8ee40e32896cbba2ca59291e2666fb69e6077
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
