# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c93ec4e3c67b3a8194095725306322a01fa4903ba1ff1d3ef0683dd2c22c066e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
