# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4b9935e32a15673f5c75621736bd15125c9c18692226157cab5b572daa05a435
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
