# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: String.t() | nil,
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
