# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentRevision do
  @moduledoc """
  A single tracked change embedded in a document.

  Populated by per-format extractors that understand change-tracking metadata
  (DOCX `w:ins`/`w:del`/`w:rPrChange`, ODT `text:change-*`, …). Every
  extractor defaults to `ExtractionResult.revisions = None` until a
  format-specific implementation is added.
  """

  @typedoc "A single tracked change embedded in a document."
  @type t :: %__MODULE__{
          revision_id: String.t() | nil,
          author: String.t() | nil,
          timestamp: String.t() | nil,
          kind: String.t() | nil,
          anchor: String.t() | nil | nil,
          delta: map()
        }

  defstruct revision_id: nil,
            author: nil,
            timestamp: nil,
            kind: :insertion,
            anchor: nil,
            delta: nil
end
