# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:16de02d9cf5c92509f47e7f3d9db815ce9240bd4828b475c926ee85ebbb762e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
