# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
