# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25ce46f7440f857d6c2b8f2f1bbfa7bf6ff35cdb9d8fcd87a5c844bb213fed21
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
