# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70b6e69e4e1764f4011ee0036d87ab7d86a78023a154379de138cf0108104af6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for DOCX"

  defstruct application: "",
            app_version: "",
            template: "",
            total_time: 0,
            pages: 0,
            words: 0,
            characters: 0,
            characters_with_spaces: 0,
            lines: 0,
            paragraphs: 0,
            company: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false
end
