# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6de9e2c4ff166a58fbeddedb103fecdd527475e496f1eb874def299517dc2e49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do
  @moduledoc "A drawing object extracted from `<w:drawing>`."

  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
