# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:57c9dfe1070c7da05dc3c03b7025641927710dc3026b4debc04c7eab7a50a546
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
