# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7409dbd3a5033a21f81dd7453d82d877bb787c8a3ab92efa3173e83aab38c69
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          filename: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer() | nil,
          is_image: boolean(),
          data: binary() | nil
        }

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
