# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9220a67582ed9de9ce10b3b905902f99a4c474a724d88cbe10b951dcaa31ea51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
