# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e3eb7f26841b9d679878469aeea21dd5107d30d868681f7f6644df75a5d1071
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  defstruct msg_fallback_codepage: 0
end
