# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7b82322dd7075a9ccde24d1e8bc1e00937bdb49af82374a4b37d03520fc0870
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Kreuzberg."

  @type t :: term()

  @type preset :: %{type: :preset, name: term()}
  @type custom :: %{type: :custom, model_id: term(), dimensions: term()}
  @type llm :: %{type: :llm, llm: term()}
  @type plugin :: %{type: :plugin, name: term()}
end
