# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:620302fc9d1541d868cfd39d2911da3d906435821ea3e4e39d89a61a4765a364
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
