# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: map()
        }

  defstruct path: nil,
            diff: nil
end
