# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Entity do
  @moduledoc "A single named entity detected in the extracted text."

  @typedoc "A single named entity detected in the extracted text."
  @type t :: %__MODULE__{
          category: String.t() | nil,
          text: String.t() | nil,
          start: non_neg_integer(),
          end: non_neg_integer(),
          confidence: float() | nil
        }

  defstruct category: :person,
            text: nil,
            start: 0,
            end: 0,
            confidence: nil
end
