# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91e7c2150e9d82e026597a3e1823ea29089493d84e9f13236a36b3870a0b84fa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
