# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:18ef08ec39e0c0ff3e12bf174762d3ef3b9aa39e493ed202a894bfc373123518
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
