# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
