# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cb846999bef59fb89ff402f8181707e1b2d6b696ce536d0191f7f0cda1cae29
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do
  @moduledoc "Extracted inline image with metadata."

  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
