# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractionResult` values."

  @typedoc "The complete diff between two `ExtractionResult` values."
  @type t :: %__MODULE__{
          content_diff: [map()],
          tables_added: [map()],
          tables_removed: [map()],
          tables_changed: [map()],
          metadata_changed: String.t() | nil,
          embedded_changes: map()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil
end
