# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractionResult` values."

  @typedoc "The complete diff between two `ExtractionResult` values."
  @type t :: %__MODULE__{
          content_diff: [map()],
          tables_added: [map()],
          tables_removed: [map()],
          tables_changed: [map()],
          metadata_changed: String.t() | nil,
          embedded_changes: map()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil
end
