# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc82f13dc0e02391dbaa659bc58b6e5f166590868ba6be683ad1213e81e3d31d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractStructuredParams do
  @moduledoc "Request parameters for LLM-based structured extraction."

  defstruct path: "",
            schema: "",
            model: "",
            schema_name: "",
            schema_description: nil,
            prompt: nil,
            api_key: nil,
            strict: false
end
