# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:179fd8a97c133069e1db6759eef284fbe198c2591f0f5e9ea7240d9ae54997ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
