# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea8c126dbf50f6dc80e04b1330ceeb307a5f8c73430bdea7f9af2a868d4389ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
