# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
          block_type: String.t() | nil,
          level: non_neg_integer() | nil,
          inline_content: [map()],
          language: String.t() | nil,
          code: String.t() | nil,
          children: [map()]
        }

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            language: nil,
            code: nil,
            children: []
end
