# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f10f6cbd92d6dcd7eaecbaf42dfd340afbb5c339e13e0c059dcebadcee8f937
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
