# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:807ca117aad89affd3d9ab33e2950315406e304678a8acea06a27b8c71958292
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
