# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5157a709a66bca9008efebdb84bbeccc65d120412c34a8ecb4c6c9c69fd098bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
