# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e600e98ae79696f07775595346d36a8c46fb6256ffb36894a247004539c25dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc "Configuration for styled HTML output."

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: "",
            embed_css: true
end
