# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44686e13be7e7a62e12d4eea7042bddad8de8869a4fdd24e87d541aebcf524de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageExtractionConfig do
  @moduledoc "Image extraction configuration."

  defstruct extract_images: true,
            target_dpi: 300,
            max_image_dimension: 4_096,
            inject_placeholders: true,
            auto_adjust_dpi: true,
            min_dpi: 72,
            max_dpi: 600,
            max_images_per_page: nil,
            classify: true
end
