# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e9a7ee54a346056f10e52507f0f49d46f8fb22754e25849c105a10a69193aa4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do
  @moduledoc "Server information response."

  defstruct version: "",
            rust_backend: false
end
