# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:66e53cf5c2c6adeaa807c31207ac01d285c6e2adefba233fee3ce9d1b9b668a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
