# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a87f7ee5df73ea6be5144321bd104687933f226299cd7fae4e895365208baf0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: "",
            yake_params: nil,
            rake_params: nil
end
