# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb4f312d4e23805d76778c527c674630514e0a1e8e06ebbc0e4251e2bb4fd726
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: "",
            yake_params: nil,
            rake_params: nil
end
