# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b2921f0f27f9d03486146a0d9d4c638fe5601b33c2707b802df45d907c6102b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
