# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93b28e362c42130d2a55a929aee36bb98c7c06752a1e726aea6d2fb67f9804d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
