# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc """
  Layout detection configuration.

  Controls layout detection behavior in the extraction pipeline.
  When set on [`ExtractionConfig`](super::ExtractionConfig), layout detection
  is enabled for PDF extraction.
  """

  @typedoc "Layout detection configuration."
  @type t :: %__MODULE__{
          confidence_threshold: float() | nil,
          apply_heuristics: boolean(),
          table_model: String.t() | nil,
          acceleration: map() | nil
        }

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
