# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2a1c752bf91c1817c975b4b0af5a608a2d034d92145c35f00e8f98e90dbe9de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutRegion do
  @moduledoc "A detected layout region on a page."

  defstruct class_name: "",
            confidence: 0.0,
            bounding_box: "",
            area_fraction: 0.0
end
