# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0d965e086a9da769ae5353fb9b39f0f87dc2f9dad472e4035409a3e547c31719
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
