# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb14524abd77986e65810efd5307ca90df46cf7d42bc4d15e8f7cfa5628cf2b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
