# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LlmBackend do
  @moduledoc "liter-llm-backed NER backend."

  alias Kreuzberg.Native

  defstruct [:ref]

  @typedoc "liter-llm-backed NER backend."
  @type t :: %__MODULE__{ref: reference()}

  def new(config) do
    ref = Native.llmbackend_new(config)
    %__MODULE__{ref: ref}
  end

  def detect(obj, text, categories) do
    Native.llmbackend_detect_async(obj.ref, text, categories)
  end

  def detect_with_custom(obj, text, categories, custom_labels) do
    Native.llmbackend_detect_with_custom_async(obj.ref, text, categories, custom_labels)
  end
end
