# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b7c0cdc52d50dc947f662cd803cfe6374efdb32f1613cbb1f3e4065cac91612
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
