# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dafb82a984f91db88b373511538d62245bb7e4549e9f4481d949c9aa9d548979
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
