# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6322e82046c0546ebb9cd32929b45ab12f0021bbb377c43e1c54b8d6f196118d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Metadata do
  @moduledoc "Extraction result metadata."

  defstruct title: "",
            subject: "",
            authors: [],
            keywords: [],
            language: "",
            created_at: "",
            modified_at: "",
            created_by: "",
            modified_by: "",
            pages: nil,
            format: :pdf,
            image_preprocessing: nil,
            json_schema: "",
            error: nil,
            extraction_duration_ms: 0,
            category: "",
            tags: [],
            document_version: "",
            abstract_text: "",
            output_format: "",
            additional: %{}
end
