# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfb647e5b04302cf5ca1ba581d0031797be395e880d88a89593d6472c3cdde8e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  defstruct det_model: "",
            cls_model: "",
            rec_model: "",
            dict_file: ""
end
