# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:805424879804ea52321383b3fd24d8caceb22b200a44e3ebbe85f2b6559175ce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
