# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81e1f88952be99f21a9a0d5cf93286c76412b61ce98332d9f8cb9e0e979761fd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfig do
  @moduledoc "OCR configuration."

  defstruct enabled: true,
            backend: "",
            language: "",
            tesseract_config: nil,
            output_format: nil,
            paddle_ocr_config: nil,
            backend_options: nil,
            element_config: nil,
            quality_thresholds: nil,
            pipeline: nil,
            auto_rotate: false,
            vlm_config: nil,
            vlm_prompt: nil,
            acceleration: nil,
            tessdata_bytes: nil
end
