# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a4857c06649a06f5d2ba377237f8951559ccb92f2a39da8e1f212f4b8b7dfc2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
