# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc48d21050039420d7f9da051ff5fb497637450f83455397aea881d2ec93b131
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
