# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e34318b9a2867514a38d2c22b5e84ef477f787a02e35df6923c6c8cf7327bab
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OdtProperties do
  @moduledoc "OpenDocument metadata from meta.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            initial_creator: "",
            keywords: "",
            description: "",
            date: "",
            creation_date: "",
            language: "",
            generator: "",
            editing_duration: "",
            editing_cycles: "",
            page_count: 0,
            word_count: 0,
            character_count: 0,
            paragraph_count: 0,
            table_count: 0,
            image_count: 0
end
