# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:945864673cc7563edd6bc967ffd2ca97b76e83f60abfd42bba6e0cd21f4e42cb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
