# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d069dcd2e8f8e0ec4b0a9fc16362f354e96c869801cca62f450bb345bfd36519
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc "Type of paginated unit in a document."

  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @spec page() :: t()
  def page, do: @page
  @spec slide() :: t()
  def slide, do: @slide
  @spec sheet() :: t()
  def sheet, do: @sheet
end
