# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e28bd7840415a54fe27c2e6c95c5372d05157fcd82cc00a52720c0ddcb7f10fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [map()]
        }

  defstruct block_count: 0,
            blocks: []
end
