# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da1e49f118cadf1b745541cb154367275fb01e1bae5e7b4b506d49541b6bfd38
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc """
  Type of paginated unit in a document.

  Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
  """

  @typedoc "Type of paginated unit in a document."
  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @doc "Standard document pages (PDF, DOCX, images)"
  @spec page() :: t()
  def page, do: @page
  @doc "Presentation slides (PPTX, ODP)"
  @spec slide() :: t()
  def slide, do: @slide
  @doc "Spreadsheet sheets (XLSX, ODS)"
  @spec sheet() :: t()
  def sheet, do: @sheet
end
