# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b24557aeea8277b5d094eff31db2fff6b9f20115f6e7df509f52c155d2d73b3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageBoundary do
  @moduledoc "Byte offset boundary for a page."

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
