# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: String.t() | nil,
          text: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            text: nil
end
