# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c964e11d4c3e92fcb6f1b56b4ed6209c0c8290d31f5a148d7709cf72717c4a8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  defstruct extract_images: false,
            extract_tables: true,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false,
            ocr_inline_images: false
end
