# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0341682d3d0c979350ef86ff4ffb8a3d779400648b8ec20b1d88b54d324e5e0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PoolError do
  @moduledoc "Error type for pool operations."

  @type t :: :lock_poisoned

  @lock_poisoned :lock_poisoned

  @spec lock_poisoned() :: t()
  def lock_poisoned, do: @lock_poisoned
end
