# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b351a0520240a307ea001088ec2b88f2ceb3a08a1361710444e3f5234785c6f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          enabled_processors: [String.t()] | nil,
          disabled_processors: [String.t()] | nil,
          enabled_set: [String.t()] | nil,
          disabled_set: [String.t()] | nil
        }

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
