# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1d67dc3c2d3d2d0b1b6373272f838e54896303cc5a04050144157dc0f600ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0,
            custom_properties: %{}
end
