# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ProcessingStage do
  @moduledoc """
  Processing stages for post-processors.

  Post-processors are executed in stage order (Early → Middle → Late).
  Use stages to control the order of post-processing operations.
  """

  @typedoc "Processing stages for post-processors."
  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @doc "Early stage - foundational processing."
  @spec early() :: t()
  def early, do: @early
  @doc "Middle stage - content transformation."
  @spec middle() :: t()
  def middle, do: @middle
  @doc "Late stage - final enrichment."
  @spec late() :: t()
  def late, do: @late
end
