# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct x: 0,
            y: 0,
            width: 0,
            height: 0
end
