# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: map() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
