# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RecognizedTable do
  @moduledoc """
  Pre-computed table markdown for a table detection region.

  Produced by the TATR-based table structure recognizer and surfaced as part of
  layout-aware OCR results.  The struct lives here (under `layout-types`, pure-Rust)
  so that consumers who do not enable `layout-detection` (ORT) can still reference
  the type in their own code.
  """

  @typedoc "Pre-computed table markdown for a table detection region."
  @type t :: %__MODULE__{
          detection_bbox: map(),
          cells: [[String.t()]],
          markdown: String.t() | nil
        }

  defstruct detection_bbox: nil,
            cells: [],
            markdown: nil
end
