# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc """
  Configuration for LLM-based structured data extraction.

  Sends extracted document content to a VLM with a JSON schema,
  returning structured data that conforms to the schema.

  # Example

  ```toml
  [structured_extraction]
  schema_name = "invoice_data"
  strict = true

  [structured_extraction.schema]
  type = "object"
  properties.vendor = { type = "string" }
  properties.total = { type = "number" }
  required = ["vendor", "total"]

  [structured_extraction.llm]
  model = "openai/gpt-4o"
  ```
  """

  @typedoc "Configuration for LLM-based structured data extraction."
  @type t :: %__MODULE__{
          schema: String.t() | nil,
          schema_name: String.t() | nil,
          schema_description: String.t() | nil,
          strict: boolean(),
          prompt: String.t() | nil,
          llm: map()
        }

  defstruct schema: nil,
            schema_name: nil,
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
