# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc """
  Configuration for LLM-based structured data extraction.

  Sends extracted document content to a VLM with a JSON schema,
  returning structured data that conforms to the schema.

  # Example

  ```toml
  [structured_extraction]
  schema_name = "invoice_data"
  strict = true

  [structured_extraction.schema]
  type = "object"
  properties.vendor = { type = "string" }
  properties.total = { type = "number" }
  required = ["vendor", "total"]

  [structured_extraction.llm]
  model = "openai/gpt-4o"
  ```
  """

  @typedoc "Configuration for LLM-based structured data extraction."
  @type t :: %__MODULE__{
          schema: String.t() | nil,
          schema_name: String.t() | nil,
          schema_description: String.t() | nil,
          strict: boolean(),
          prompt: String.t() | nil,
          llm: map()
        }

  defstruct schema: nil,
            schema_name: nil,
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
