# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:94eacd8a852bc4d1d3bc4e4c51d0a4c5ce73cbe1ec1dcfffee1ccba7132011c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @type t :: :json_ld | :microdata | :rd_fa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rd_fa

  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @spec microdata() :: t()
  def microdata, do: @microdata
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
