# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c97e32ba03b115492218173cb4868c565a79f06f83193bb3f6764e2b44a7b9c8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StyleDefinition do
  @moduledoc "A single style definition parsed from `<w:style>` in `word/styles.xml`."

  defstruct id: "",
            name: nil,
            style_type: "",
            based_on: nil,
            next_style: nil,
            is_default: false,
            paragraph_properties: "",
            run_properties: ""
end
