# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ed893cd21cf015ca10a201af02ca92d16f9d3a21e43233eed32e7f9effece4c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
