# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d32c6d6cc1c00762f2611061bc8caed70df55fe0fc508ee47ef937dc1280b79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Kreuzberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
