# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:199d1035eaa205e5d1b57e03d4c14d38bab9dbc53563245a77787d6aaa9b9190
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc "Structured table grid with cell-level metadata."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
