# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Table do
  @moduledoc """
  Extracted table structure.

  Represents a table detected and extracted from a document (PDF, image, etc.).
  Tables are converted to both structured cell data and Markdown format.
  """

  @typedoc "Extracted table structure."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
