# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dd26c37fb3963e258074bf1fe6bb781765e16b30800744e2dd56ca02b9080e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextDirection do
  @moduledoc "Text direction enumeration for HTML documents."

  @type t :: :left_to_right | :right_to_left | :auto

  @left_to_right :left_to_right
  @right_to_left :right_to_left
  @auto :auto

  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @spec auto() :: t()
  def auto, do: @auto
end
