# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            kind: :bold
end
