# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61d44d2b9e8b34b9a49567baa3323d9935d391f716ee5b09f93f7c0706dd69f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            kind: :bold
end
