# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f20781567ad5d1e82f61b068646bc7c41fe03c83e6e6c949a7c84267bcf491
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TextDirection do
  @moduledoc "Text direction enumeration for HTML documents."

  @typedoc "Text direction enumeration for HTML documents."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text direction"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text direction"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic text direction detection"
  @spec auto() :: t()
  def auto, do: @auto
end
