# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf166bcce08079d56070b82ea4ad42778885bdf29481a1dc991daf7f8318c121
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
