# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenReductionConfig do
  @moduledoc "Configuration for the token-reduction pipeline."

  @typedoc "Configuration for the token-reduction pipeline."
  @type t :: %__MODULE__{
          level: String.t() | nil,
          language_hint: String.t() | nil,
          preserve_markdown: boolean(),
          preserve_code: boolean(),
          semantic_threshold: float(),
          enable_parallel: boolean(),
          use_simd: boolean(),
          custom_stopwords: map() | nil,
          preserve_patterns: [String.t()],
          target_reduction: float() | nil,
          enable_semantic_clustering: boolean()
        }

  defstruct level: :moderate,
            language_hint: nil,
            preserve_markdown: false,
            preserve_code: true,
            semantic_threshold: 0.3,
            enable_parallel: true,
            use_simd: true,
            custom_stopwords: nil,
            preserve_patterns: [],
            target_reduction: nil,
            enable_semantic_clustering: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
