# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eaab7e139fa409d08b172bdb59226a57e74d180157bafe51c75814b59d20b026
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TracingLayer do
  @moduledoc "A [`tower::Layer`] that wraps each extraction in a semantic tracing span."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tracinglayer_default()}
  end
end
