# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bd3b21f8ae1157a674d20836ce013257eabc364905351ad8a4b285b58664ce8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc "Processing options for tree-sitter code analysis."

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
