# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0707d32212c8114b1aecc9984cae1f0ba0e072c667e7a49471710fa7fa54287
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.UriKind do
  @moduledoc "Semantic classification of an extracted URI."

  @type t :: :hyperlink | :image | :anchor | :citation | :reference | :email

  @hyperlink :hyperlink
  @image :image
  @anchor :anchor
  @citation :citation
  @reference :reference
  @email :email

  @spec hyperlink() :: t()
  def hyperlink, do: @hyperlink
  @spec image() :: t()
  def image, do: @image
  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec citation() :: t()
  def citation, do: @citation
  @spec reference() :: t()
  def reference, do: @reference
  @spec email() :: t()
  def email, do: @email
end
