# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c51ec24435ba30bf5eae9b522f0a4b77712b52547253a6e9a128c9eed11ee3d4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
