# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6c1cd410442911525b710432b2363a288f36c46669e527d50378aa54b63220e4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
