# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f2e41a3d61099468728981ccce00576739de7d168d14dc3a2de13d6312b50f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
