# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1899cd183fff1596b944ebee4ed87ebcc4bb5840be234979b66f9a50cdf620dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  @typedoc "YAKE-specific parameters."
  @type t :: %__MODULE__{
          window_size: non_neg_integer()
        }

  defstruct window_size: 2

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
