# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f9ab597355d17e379e622b566fbee77cdb94f0f5196c9c89082b73be01e1173
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
