// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:840f77a7018f19426bfea410824dd4902fc856820293babe322c5ef6893103c4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  clearEmbeddingBackends,
  listEmbeddingBackends,
  WasmLayoutDetectionConfig,
  WasmChunkingConfig,
  WasmOcrPipelineStage,
  WasmTokenReductionOptions,
  WasmKeywordConfig,
  WasmPdfConfig,
  WasmImagePreprocessingConfig,
  WasmHtmlOutputConfig,
  WasmPostProcessorConfig,
  WasmImageExtractionConfig,
  WasmPageConfig,
  WasmLlmConfig,
  WasmContentFilterConfig,
  WasmSecurityLimits,
  WasmAccelerationConfig,
  WasmOcrQualityThresholds,
  WasmStructuredExtractionConfig,
  WasmRakeParams,
  WasmTreeSitterConfig,
  WasmTreeSitterProcessConfig,
  WasmEmbeddingConfig,
  WasmOcrPipelineConfig,
  WasmEmailConfig,
  WasmYakeParams,
  WasmTesseractConfig,
  WasmOcrElementConfig,
  WasmHierarchyConfig,
  WasmOcrConfig,
  WasmLanguageDetectionConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("embedding_backend_management", () => {
  it("embedding_backends_clear: Clear all embedding backends and verify list is empty", () => {
    clearEmbeddingBackends();
  });
  it("embedding_backends_list: List all registered embedding backends", () => {
    listEmbeddingBackends();
  });
});
