// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0911bf711ffca9df54576a66f8b4d66ca4e07e9d0209c4c3dfa698b2add59a4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  getExtensionsForMime,
  WasmLayoutDetectionConfig,
  WasmChunkingConfig,
  WasmOcrPipelineStage,
  WasmKeywordConfig,
  WasmTokenReductionOptions,
  WasmImagePreprocessingConfig,
  WasmPdfConfig,
  WasmPostProcessorConfig,
  WasmHtmlOutputConfig,
  WasmImageExtractionConfig,
  WasmPageConfig,
  WasmLlmConfig,
  WasmContentFilterConfig,
  WasmSecurityLimits,
  WasmAccelerationConfig,
  WasmOcrQualityThresholds,
  WasmStructuredExtractionConfig,
  WasmRakeParams,
  WasmTreeSitterConfig,
  WasmTreeSitterProcessConfig,
  WasmEmbeddingConfig,
  WasmOcrPipelineConfig,
  WasmEmailConfig,
  WasmYakeParams,
  WasmTesseractConfig,
  WasmOcrElementConfig,
  WasmHierarchyConfig,
  WasmOcrConfig,
  WasmLanguageDetectionConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("registry_operations", () => {
  it("extensions_docx: Get file extensions for DOCX MIME type", () => {
    getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  });
  it("extensions_html: Get file extensions for HTML MIME type", () => {
    getExtensionsForMime("text/html");
  });
  it("extensions_pdf: Get file extensions for PDF MIME type", () => {
    const result = getExtensionsForMime("application/pdf");
    expect(result).toContain("pdf");
  });
});
