# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0709258e4c963b853d48ca8cad9d2638452c5ca4af6d1751f3b657e0a93403f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'document_extractor_management' do
  it 'document_extractors_clear: Clear all document extractors and verify list is empty' do
    Kreuzberg.clear_document_extractors()

  end

  it 'extractors_list: List all registered document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end
end
