# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0e926041f6041a04037b01f125c46c1f5f98f1d6aff8656245fb8d0ce7fea9d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'document_extractor_management' do
  it 'document_extractors_clear: Clear all document extractors and verify list is empty' do
    Kreuzberg.clear_document_extractors()

  end

  it 'extractors_list: List all registered document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end
end
