# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a48c5014f2c2a534096f2b45f8c6c14623e64ee01feb6ace4673aa2e1b33c25
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embed_extra' do
  it 'embed_texts_batch: Batch embed texts' do
    result = Kreuzberg.embed_texts_async(['Hello', 'World'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
