# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d034b4b2e4c9e85087a0c9b3e386990649131ff71b589e58ed1c7ba9fdcc0b4a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'pdf' do
  it 'render_pdf_page_first: render_pdf_page_to_png: first page' do
    pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
    result = Kreuzberg.render_pdf_page_to_png(pdf_bytes, 0)
    expect(result.length).to be >= 100

  end

  it 'render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range' do
    expect {
      pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
      Kreuzberg.render_pdf_page_to_png(pdf_bytes, 999)
    }.to raise_error
  end
end
