# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'registry' do
  it 'list_document_extractors: List document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end

  it 'list_embedding_backends: List embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

  it 'list_ocr_backends: List OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'list_post_processors: List post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end

  it 'list_renderers: List renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end

  it 'list_validators: List validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
