# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'registry' do
  it 'list_document_extractors: List document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end

  it 'list_embedding_backends: List embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

  it 'list_ocr_backends: List OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'list_post_processors: List post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end

  it 'list_renderers: List renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end

  it 'list_validators: List validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
