# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a54eef2a6e8d80a1da3ad4490bef4f21628c4ae6869f99be1c9f61e9eed1b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'summarization' do
  it 'summarization_extractive_smoke: TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.' do
    result = Kreuzberg.extract_file_sync('text/book_war_and_peace_1p.txt', nil, Kreuzberg::ExtractionConfig.new(summarization: { 'max_tokens' => 80, 'strategy' => 'extractive' }))
    expect(result.mime_type.to_s.strip).to eq('text/plain'.strip)
    # skipped: field 'summary.text' not available on result type
    # skipped: field 'summary.strategy' not available on result type

  end
end
