// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:952c81fc58b277486b8c4e15750881d7a654b360e601642fee11605e15305109
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';

// E2e tests for category: smoke
void main() {
  test('OCR: PNG image extraction with OCR enabled. In WASM this exercises the Uint8Array bridge parameter and Promise await in the generated OcrBackend bridge.', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'ocr_image_png\'');
  });

  test('Smoke test: DOCX with formatted text', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_docx_basic\'');
  });

  test('Smoke test: HTML table extraction', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_html_basic\'');
  });

  test('Smoke test: JSON file extraction', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_json_basic\'');
  });

  test('Smoke test: PDF with simple text extraction', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_pdf_basic\'');
  });

  test('Smoke test: Plain text file', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_txt_basic\'');
  });

  test('Smoke test: XLSX with basic spreadsheet data including tables', () {
    markTestSkipped('TODO: implement Dart e2e test for fixture \'smoke_xlsx_basic\'');
  });

}
