// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7eb73f5445cd12e501eff6a606dfe037651b37e450189a7605b380b5bec1eb08
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: validator_management
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Clear all validators and verify list is empty', () async {
    final result = await KreuzbergBridge.clearValidators();
  });

  test('List all registered validators', () async {
    final result = await KreuzbergBridge.listValidators();
  });

}
