// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20e9b49d8d23a2536d77b249d8daa3a515231241baed0dd84825c5c37e301cad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: document_extractor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_DocumentExtractorsClear(t *testing.T) {
	// Clear all document extractors and verify list is empty
	_ = kreuzberg.ClearDocumentExtractors()
}

func Test_ExtractorsList(t *testing.T) {
	// List all registered document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
