// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f2a6dd59e9ee4ab5ba31b9de4b525cc0baf389756e133efefd3bcb86865cef11
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: embed_extra
package e2e_test

import (
	"encoding/json"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbedTextsBatch(t *testing.T) {
	// Batch embed texts
	var texts []string
	if err := json.Unmarshal([]byte(`["hello","world"]`), &texts); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	var config kreuzberg.EmbeddingConfig
	if err := json.Unmarshal([]byte(`{"model":{"name":"balanced","type":"preset"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.EmbedTexts(texts, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
