// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d51f66334669e8f169af0634b5c586036632f173fc1dcd055d6e3befcb20be4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = kreuzberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
