// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aae41ac36f03142a150dd7fabe912bf834fff103fa2b763a7fd6e588b4a71d2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	_ = kreuzberg.ClearValidators()
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := kreuzberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
