// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b49b14d0ec0a6b314d748f27e166a0af069411133897908402a431cf7c07922a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {
    @Test
    fun testEmbeddingBackendsList() = runBlocking {
        // List all registered embedding backends
        val result = Kreuzberg.listEmbeddingBackends()
    }

}
