// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0aa9c7c551d964c3805130f5d88e6423fe12456e2db8d92ce10bb39f448e46e7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: mime_utilities. */
class MimeUtilitiesTest {
    @Test
    fun testMimeDetectBytes() = runBlocking {
        // Detect MIME type from file bytes
        val result = Kreuzberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("pdf/fake_memo.pdf")))
        // skipped: field 'result' not available on result type
    }

    @Test
    fun testMimeDetectImage() = runBlocking {
        // Detect MIME type from PNG image bytes
        val result = Kreuzberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("images/test_hello_world.png")))
        // skipped: field 'result' not available on result type
    }

    @Test
    fun testMimeGetExtensions() = runBlocking {
        // Get file extensions for a MIME type
        val result = Kreuzberg.getExtensionsForMime("application/pdf")
        // skipped: field 'result' not available on result type
    }

}
