// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e94ff648e05b5602126c29f0ae7f57bae6e0e174b146806c1c4b7ed88ba79701
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: ocr_backend_management. */
class OcrBackendManagementTest {
    @Test
    fun testOcrBackendsList() = runBlocking {
        // List all registered OCR backends
        val result = Kreuzberg.listOcrBackends()
    }

}
