// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1009b9b650e4e09570d1f3641aa89405eb010ee94f45bb99dbf7a30b60a6adfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {
    @Test
    fun testValidatorsClear() = runBlocking {
        // Clear all validators and verify list is empty
        val result = ValidatorBridge.clearAll()
    }

    @Test
    fun testValidatorsList() = runBlocking {
        // List all registered validators
        val result = Kreuzberg.listValidators()
    }

}
